### PR TITLE
fix(#3966): account for network errors

### LINKED ISSUE #3966: Is retry interceptor only retry http error and ignore dns error？
## Bug Description

I found undici built-in retry interceptor will only retry http error and ignore dns error. Is this a bug or feature?

## Reproducible By

```js
const { interceptors, Client } = require('undici');
const { retry } = interceptors;

(async () => {
  const client = new Client().compose(
    // httpbin/status/500 will return http status 500 so retry callback will trigger
    'https://httpbin.org',
    // x.y.z is a not reachable server will cause a ENOTFOUND error
    // but will not trigger retry callback
    // 'https://x.y.z',
    retry({
      retry: (err, { state, opts }, done) => {
        console.log('#retry-callback triggered');
      },
      errorCodes: ['ENOTFOUND'],
    }),
  );

  const response = await client.request({
    method: 'GET',
    path: '/status/500',
    headers: {
      'content-type': 'application/json',
    },
  });
})();
```

- undici version: 7.1.1

## Expected Behavior

Retry callback log be triggered whether host is `httpbin.org` or `x.y.z`.

But actual behavior is only `httpbin.org` will trigger retry.

## Environment

- Node.js v22.11.0

### Additional context

According to the [retry-handler doc](https://github.com/nodejs/undici/blob/main/docs/docs/api/RetryHandler.md#parameter-dispatchdispatchoptions--retryoptions), retry handler has an option `errorCodes` means "Array of Error codes to retry", so retry dns error is expected in design?

But in code, retry handler will skip retry in onResponseError hook [when controller is falsy](https://github.com/nodejs/undici/blob/3eeeeb79b9b890cce39607016fd9e91d235c7134/lib/handler/retry-handler.js#L279C1-L283C6).

Controller was pass to onResponseError hook in [onError hook](https://github.com/nodejs/undici/blob/3eeeeb79b9b890cce39607016fd9e91d235c7134/lib/handler/unwrap-handler.js#L89C1-L95C4),

but controller was only  initialized at [onConnect hook](https://github.com/nodejs/undici/blob/3eeeeb79b9b890cce39607016fd9e91d235c7134/lib/handler/unwrap-handler.js#L65C1-L68C4).

I guess there is no connection established when dns error, so onConnect will not be trigger, which leading controller is undefined.

### PR DESCRIPTION
**Pull request by metcoder95**
## This relates to...

Closes #3966

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Ethan-Arrowood — APPROVED** [review]
lgtm

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by remidewitte** [comment]
Thanks.

Do you think it would also work for EHOSTUNREACH errors ?

**Comment by metcoder95** [comment]
Yes, it should!

**Pull request merged**
