### PR TITLE
fix: add missing maxRedirections type definition

### PR DESCRIPTION
**Pull request by fraxken**
PR to fix issue reported in #858

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Comment by fraxken** [comment]
Oh yeah my bad didn't see that they were UT for types too.

**Comment by fraxken** [comment]
Ok just made an attempt (not sure if this is ok because first time doing UT for types ^^).

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
