### PR TITLE
fix: support `ArrayBufferView` and `ArrayBuffer` as body

### PR DESCRIPTION
**Pull request by LiviaMedeiros**
Implementation-wise, do we really need to make a copy?

### CODE REVIEW

**Review by ronag — CHANGES_REQUESTED** [review]
Needs a test

**Comment by KhafraDev** [comment]
> Implementation-wise, do we really need to make a copy?

Yes, see [extract](https://fetch.spec.whatwg.org/#concept-bodyinit-extract):
```
BufferSource]

    Set source to a copy of the bytes held by object.
```

**Comment by LiviaMedeiros** [comment]
> Set source to a copy of the bytes held by object.

This is true spec-wise, but seems costly in implementation. I wonder if there is a workaround with better performance, considering that most other implementations do not expose `Request.body` directly.

Anyway, even if it's possible to optimize later, working code and spec compliance goes first.

**Review by KhafraDev — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
ping @ronag

**Pull request merged**
