### PR TITLE
types: Refine internal TS export/imports to be more robust

### LINKED ISSUE #1727: esModuleInterop flag required to build TypeScript project referencing v5.11.0
## Bug Description

Starting in v5.11.0, it seems like the "esModuleInterop" flag is required to get a TypeScript build passing for a project referencing undici. It worked just fine in 5.10.0, and I believe the change to the types files occurred in the following PR by @arontsang, but I'm not sure if it was intentional: https://github.com/nodejs/undici/pull/1338

## Reproducible By

1. Clone this simple app: https://github.com/ejizba/undicibug
2. Run `npm install`
3. Run `npm build`

## Expected Behavior

The build passes

## Actual Behavior

The build fails with these errors:

```
node_modules/undici/types/client.d.ts:5:8 - error TS1259: Module '"/undiciBug/node_modules/undici/types/connector"' can only be default-imported using the 'esModuleInterop' flag

5 import buildConnector, {connector} from "./connector";
         ~~~~~~~~~~~~~~

  node_modules/undici/types/connector.d.ts:4:1
    4 export = buildConnector
      ~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/undici/types/dispatcher.d.ts:6:13 - error TS1259: Module '"/undiciBug/node_modules/undici/types/readable"' can only be default-imported using the 'esModuleInterop' flag

6 import type BodyReadable from './readable'
              ~~~~~~~~~~~~

  node_modules/undici/types/readable.d.ts:4:1
    4 export = BodyReadable
      ~~~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/undici/types/handlers.d.ts:1:8 - error TS1259: Module '"/undiciBug/node_modules/undici/types/dispatcher"' can only be default-imported using the 'esModuleInterop' flag

1 import Dispatcher from "./dispatcher";
         ~~~~~~~~~~

  node_modules/undici/types/dispatcher.d.ts:12:1
    12 export = Dispatcher;
       ~~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

## Environment

Mac
Node 18

### Additional context

I can work around the bug by setting `esModuleInterop` to `true` in the sample app linked above, but unfortunately that flag causes other problems in my "real" app 😮‍💨

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #1727

From my understanding, this shouldn't be a semver major, as public types should stay the same.

### CODE REVIEW

**Review by KhafraDev — APPROVED** [review]

**Comment by kibertoad** [comment]
@mcollina As there are two important TS fixes in main which are addressing breaking changes in semver minor, maybe it would be possible to publish new version?

**Comment by antonstefer** [comment]
This has moved `HttpMethod` which is a public type to `Dispatcher`. Maybe it should have been a semver major

**Comment by KhafraDev** [comment]
It's still under Dispatcher, https://github.com/nodejs/undici/blob/f6323f67e64721e86b9c02b718c7d370b18ca25b/types/dispatcher.d.ts#L215. Do you have an example of what's not working? I don't think type changes are ever considered major changes due to the nature of typescript.

**Comment by antonstefer** [comment]
dispatcher has been made the default export, so HttpMethod can't be directly imported anymore. I prefer the way it's done now but it breaks imports like
`import type { HttpMethod } from 'undici/types/dispatcher'`

**Comment by kibertoad** [comment]
`import type { HttpMethod } from 'undici/types/dispatcher'`

this very much looks like importing an internal type. Public types are in `undici`.

**Comment by antonstefer** [comment]
I would still suggest adding it to the changelog in a more explicit way

**Pull request merged**
