### PR TITLE
fix: move CNAME and .nojekyll to root

### PR DESCRIPTION
**Pull request by Uzlopak**
currently the website is broken. the workflow to deploy is using jekyll for some reason. Maybe .nojekyll must be in root?
Also moving CNAME to root. 

@Ethan-Arrowood

### CODE REVIEW

**Review by Ethan-Arrowood — APPROVED** [review]
Oh I didn't realize the docs move got merged. Yes - we also have to change repo settings

**Comment by Uzlopak** [comment]
Should we merge and in the hope it fixes the page?

**Comment by Ethan-Arrowood** [comment]
yeah - I'm at my computer now and I can fix this

**Comment by Uzlopak** [comment]
@Ethan-Arrowood 
Should I stay up to approve potential PRs?

**Comment by Uzlopak** [comment]
YAY. Its up and running

**Comment by Ethan-Arrowood** [comment]
Nah I just pushed to main for this. Want to keep disruption to minimum. All should be restored now

**Comment by Uzlopak** [comment]
docs/docs is looking funny :D

but yeah, better having the website running. do you want to take care of renaming it documentation, or is this something we have to live with?

Anyhow. I go to sleep now ;)

**Comment by Ethan-Arrowood** [comment]
Problem for another day

**Pull request merged**
