### PR TITLE
feat: make the dispatcher truly global

### PR DESCRIPTION
**Pull request by mcollina**
Fixes: #1331

### CODE REVIEW

**Comment by targos** [comment]
`index-fetch.js` will have to be updated too if we want to use the same dispatcher in Node.js.

**Comment by mcollina** [comment]
@targos done

**Comment by ronag** [comment]
Ci failing?

**Comment by mcollina** [comment]
my bad, pushing a fix.

**Comment by mcollina** [comment]
Closing because for some reason Github is not showing my commit.

**Pull request closed without merging**
