### PR TITLE
fix: unsafe methods should result in cache purge

### PR DESCRIPTION
**Pull request by Uzlopak**
the problem is, that the cache invalidation logic is done in cache-handler.js. So it makes no sense to avoid calling the cache logic, if the method is unsafe. All requests with origin have to go through the cache logic.

@flakey5

### CODE REVIEW

**Review by flakey5 — CHANGES_REQUESTED** [review]
This allows safe methods to purge the cache if they aren't included in `methods`. While this isn't stated in the spec, only unsafe methods should cause cache purges imo

i.e. add
```javascript
await client.request({
  origin: 'localhost',
  method: 'HEAD',
  path: '/'
})

strictEqual(deleteByOriginCalled, false)
```
to the test _before_ the `DELETE` request and the test will fail

**Comment by Uzlopak** [comment]
You implemented the interface and added the methods attribute. If this attribute is an artifact, than we should remove it.

**Comment by Uzlopak** [comment]
I think it works as expected. Maybe methods should be renamed to safeMethods?

**Comment by flakey5** [comment]
> Maybe methods should be renamed to safeMethods?

That still wouldn't fix the issue of safe methods being able to purge the cache?

**Comment by Uzlopak** [comment]
closing for now

**Pull request closed without merging**
