### PR TITLE
fix: eslint + prettier config

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
@Ethan-Arrowood @dnlup

**Review by mcollina — CHANGES_REQUESTED** [review]
I think this change is unnecessary and it hampers delivering quality software on multiple lines. Backporting commits after this land will become more complicated.

**Comment by ronag** [comment]
No strong opinion other than it would have been nice.

**Comment by Ethan-Arrowood** [comment]
Id rather we stick to standard like we already are.

**Pull request closed without merging**
