### PR TITLE
fix: force gc on request pause

### PR DESCRIPTION
**Pull request by ronag**
Refs: #998

### CODE REVIEW

**Comment by mcollina** [comment]
I'm -0 on this - I would never rely on `global.gc()` and the people that would need this behavior won't know to pass it either.

However this needs a test.

**Comment by ronag** [comment]
Maybe once/if we land in core.

**Comment by ronag** [comment]
@addaleax would be nice if there was a way to access global.gc without the cli flag :)

**Comment by addaleax** [comment]
@ronag There’s always been good reasons not to expose that, though.

**Comment by ronag** [comment]
> @ronag There’s always been good reasons not to expose that, though.

Indeed. Probably more reasons not to expose. But this is at least one possible reason to expose. 😄

**Pull request closed without merging**
