### PR TITLE
Embed llhttp

### PR DESCRIPTION
**Pull request by dnlup**
Follows #575

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Comment by dnlup** [comment]
I tried the GitHub UI for resolving the conflicts but now we have a merge commit, sorry

**Review by mcollina — CHANGES_REQUESTED** [review]
The `deps` must not be included in the final released module. I have a feeling that would be too big. We should just ship the wasm.

**Comment by dnlup** [comment]
> The `deps` must not be included in the final released module. I have a feeling that would be too big. We should just ship the wasm.

Yes definitely, I missed it, thanks. Should we merge #601 before and then rebase the changes here?

**Comment by mcollina** [comment]
> Yes definitely, I missed it, thanks. Should we merge #601 before and then rebase the changes here?

I think so.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
