### PR TITLE
fix: bad client destroy on servername change

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/3065

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by ronag** [comment]
@metcoder95 any chance you can help me with a test?

**Review by metcoder95 — APPROVED** [review]
Done @ronag can you take a look?

**Comment by metcoder95** [comment]
I'll work for adding a test for h2 in another PR 👍

**Review by Uzlopak — APPROVED** [review]
LGTM

**Pull request merged**
