### PR TITLE
feat: support long polling requests and event-source responses

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
Needs tests

**Comment by ronag** [comment]
This logic is only relevant when pipelining > 1 and ensures that no more requests are enqueued.

**Comment by MetCoder95** [comment]
This is an implementation of SSR or pure long-polling? (I'm asking because I see the `text/event-stream` header involved) :)

**Review by mcollina — COMMENTED** [review]
wow!

**Pull request closed without merging**
