### PR TITLE
chore: automate releases with pr

### PR DESCRIPTION
**Pull request by mweberxyz**
## This relates to...

https://github.com/nodejs/undici/issues/3042

## Changes
Add two new github workflows: Create release PR, and Release.

Create release PR action is executed manually by a maintainer. It will take main, bump the version number as desired (either explicit, major, minor, or patch) and create a PR to be approved and merged.

Release action runs on all changes to main that change the package.json file.
If the version number has not changed, it immediately exits.
Otherwise, it publishes to NPM then creates a GitHub release.

## Demo
In my fork I made three changes from the head commit:
1. changing the package.json `name` to a package which I control
2. Commenting out the `undici-types` publish steps
3. Remove npm provenance check.

Then,

### Created a sample issue and PR
This PR made a non-version-bumping change to package.json to ensure the release workflow did not run.

PR: https://github.com/mweberxyz/nodejs-undici/pull/16

See https://github.com/mweberxyz/nodejs-undici/actions/runs/8637094971 for the workflow run upon merge to main. Note the "release" step is skipped. The entire workflow would have been skipped had the package.json not been changed.

### Ran the create PR workflow

CleanShot 2024-04-10 at 16 02 50@2x

Create PR workflow run: https://github.com/mweberxyz/nodejs-undici/actions/runs/8637108281

PR created automatically: https://github.com/mweberxyz/nodejs-undici/pull/17

### Merged the PR created by the create PR workflow

Workflow run upon merge to main: https://github.com/mweberxyz/nodejs-undici/actions/runs/8637133400

Which created the releases:
- https://www.npmjs.com/package/@mweberxyz/undici?activeTab=versions
- https://github.com/mweberxyz/nodejs-undici/releases/tag/v6.15.1

### Checkboxes
- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [x] Review ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by mweberxyz** [comment]
Little annoyance noticed: the release notes contain the release commit itself. I will strip those off.

**Comment by mcollina** [comment]
> Little annoyance noticed: the release notes contain the release commit itself. I will strip those off.

Can you articulate?

**Comment by mweberxyz** [comment]
> > Little annoyance noticed: the release notes contain the release commit itself. I will strip those off.
> 
> Can you articulate?

If you take a look at the [release notes for the test release](https://github.com/mweberxyz/nodejs-undici/releases/tag/v6.15.1):

CleanShot 2024-04-11 at 11 37 23@2x

The auto-generated release notes include all PRs, including the PR which bumped the version in package.json. It's not a show stopper, but seems a bit duplicative - would be preferred if that line wasn't there imo.

**Comment by mweberxyz** [comment]
@mcollina ptal at three additional commits

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
