### PR TITLE
feat: implement fetch API

### PR DESCRIPTION
**Pull request by ronag**
This ports the `fetch` API from https://github.com/Ethan-Arrowood/undici-fetch (i.e. without exposing `Request` and `Response`).

### CODE REVIEW

**Comment by ronag** [comment]
We should probably mark certain things as experimental here until we are sure about spec compliance:

- Redirects
- Response.formData()
- Response.clone()
- Request.integrity
- Request.keepalive

**Comment by ronag** [comment]
@Ethan-Arrowood Please contact me when you have time so we can discuss and coordinate this PR and undici-fetch.

**Comment by ronag** [comment]
@mcollina: This feature does need more polish but I would like to merge and publish it as experimental as I believe we can probably get more engagement and contributions from the community on this. Especially since it's a highly requested feature. People can play around with it and report issues we should fix.

I was thinking we could make an issue with a check list of things that people can contribute with for us to promote if from experimental status, e.g:

- Spec compliance reports
  -  redirect compliance
- Types
- Docs
- Tests + Coverage
- Port/Merge e.g. tests from undici-fetch.
- Port of WPT tests
- `redirect` option with `"error"` and `"manual"`
- `integrity` option
- `Response.clone`

The idea here to begin with is to only implement the `fetch` API, i.e. we don't export `Response`, `Request` and `Header` classes. That can be a second step.

@mcollina @Ethan-Arrowood wdyt?

**Comment by mcollina** [comment]
Could this be implemented without breaking changes elsewhere?

**Comment by ronag** [comment]
> Could this be implemented without breaking changes elsewhere?

I think so. Did you see a breaking change somewhere?

**Comment by Ethan-Arrowood** [comment]
Hey @ronag sorry I'm just getting to this PR now. Happy to chat on what else needs to be done and anyway i can help!

**Pull request merged**
