### PR TITLE
fix: add wpts to code coverage

### PR DESCRIPTION
**Pull request by KhafraDev**
Refs: #951 

I have no idea if this works.

### CODE REVIEW

**Comment by KhafraDev** [comment]
Looks like I can't test this until the CI works for node 19 😕 
https://app.codecov.io/gh/nodejs/undici/pull/1734

```
You will see an error stating No coverage uploaded for pull request head. when the pull request has:
    ...
    or the uploaded reports are from failed CI builds.

```

**Comment by ronag** [comment]
Try removing 19 from the test matrix

**Comment by KhafraDev** [comment]
well I guess it doesn't work

**Comment by KhafraDev** [comment]
honestly I don't know

**Comment by KhafraDev** [comment]
Here's the predicament: 
- nyc doesn't support esm (which is why it shows no coverage for WPTs)
- tap doesn't support c8, only nyc

So the only option is to replace esm in the WPT runner with cjs.

**Pull request closed without merging**
