### PR TITLE
change `statusCode` to `status`

### PR DESCRIPTION
**Pull request by renhiyama**
I dont see `statusCode` in the request. Instead I see `status`:
image

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by metcoder95** [comment]
Thanks for the contribution!
Do you have a reproducible example we can take a look at?

The `status` is scoped to the usage of `fetch` due to the spec, you should find `statusCode` otherwise.

**Comment by renhiyama** [comment]
> Thanks for the contribution! Do you have a reproducible example we can take a look at?
> 
> The `status` is scoped to the usage of `fetch` due to the spec, you should find `statusCode` otherwise.

```js
let req = await fetch("https://httpstat.us/500");
console.log(req);
```
I'm running this code on node v18+

It logs `status` again instead of `statusCode`

**Review by KhafraDev — CHANGES_REQUESTED** [review]
the docs are using `undici.request`, not fetch.

**Comment by renhiyama** [comment]
Alright.

**Pull request closed without merging**
