### PR TITLE
fix windows CI

### LINKED ISSUE #2378: Windows CI: The syntax of the command is incorrect.
windows 18 & 20 consistently fail 80% of the way into the WPTs with ` The syntax of the command is incorrect.`

the fix might be to replace the forward slashes for paths with `\\`, but then it won't work on other platforms.

https://github.com/nodejs/undici/blob/3ec35ee23a7f2693bd6f9f707f6a20dc6de7a6b0/package.json#L87

### PR DESCRIPTION
**Pull request by KhafraDev**
Fixes #2378

### CODE REVIEW

**Comment by KhafraDev** [comment]
yeah so that works, I have no idea why removing the options passed to node would matter, but...

**Comment by panva** [comment]
FYI This PR has removed websockets from the WPT report again.

**Comment by panva** [comment]
And adding the `--experimental-websocket` option to your npm script will not work because presence of that option will make the daily WPT job error on older versions of node where the option didn't land.

**Comment by KhafraDev** [comment]
why did we need the flag?

**Comment by panva** [comment]
To allow detecting that the feature was present on a particular node build that's being used in the WPT job matrix

**Comment by KhafraDev** [comment]
I think it can be replaced with a version check instead

**Comment by panva** [comment]
> I think it can be replaced with a version check instead

If you want to maintain that, sure, I didn't.

**Pull request merged**
