### PR TITLE
feat: implement `FormData Iterator`

### PR DESCRIPTION
**Pull request by KhafraDev**
Continuation of #1431 and #1423 

Also adds in `FormData.forEach` which was added in the types but for some reason wasn't implemented.

### CODE REVIEW

**Comment by kibertoad** [comment]
What's missing before this can be merged?

**Comment by KhafraDev** [comment]
A review from ronag, who is currently on vacation I presume 😄

**Comment by mcollina** [comment]
> A review from ronag I presume, who is currently on vacation 😄

pretty much

**Comment by jimmywarting** [comment]
Hmm, tried doing `export const FormData = globalThis.FormData || polyfill` but notices that hour tests failed failed cuz this forEach was missing...

was using NodeJS 18.3.0

have a resent nodejs release been released with this fix?

**Comment by KhafraDev** [comment]
@jimmywarting v18.5.0 has `FormData.prototype.forEach`.

**Pull request merged**
