### PR TITLE
fix aborting Streams

### PR DESCRIPTION
**Pull request by epistemancering**
## This relates to...
https://github.com/nodejs/undici/issues/1711
## Rationale
The simple fix to the memory issue caused a worse issue. Common patterns that involve catching AbortErrors, such as retrying slow requests, silently fail if the signal unluckily happens to be aborted during the read. A proper fix to the memory issue will likely be more involved.
## Changes
revert https://github.com/nodejs/undici/pull/2823/commits/49e33a87411b003705e377a8d5ea6d2d1acef108
### Bug Fixes
Aborting a Stream doesn't throw.
```javascript
const abortController = new AbortController

;(async () => {
    const readStream = (await fetch("https://www.googleapis.com/customsearch/v1", { signal: abortController.signal })).arrayBuffer()

    setTimeout(() => {
        abortController.abort()
    })

    await readStream
})()
```
## Status
- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [x] Review ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by KhafraDev — CHANGES_REQUESTED** [review]
This is missing a test and is replacing one issue for another. I will take a look in a few days.

**Comment by KhafraDev** [comment]
I need a test case that doesn't use a third party endpoint to work on it. The case you provided doesn't abort in node or Deno, and I cannot test in browsers because of CSP.

The correct fix, afaict, is to remove the *previous* listener if > 1 exists (such that 1 listener always exists) or to only add a listener if there are none.

**Comment by epistemancering** [comment]
```javascript
import * as http from "http"

const abortStream = async () => {
    const abortController = new AbortController
    const readStream = (await fetch("http://localhost", { signal: abortController.signal })).arrayBuffer()
    abortController.abort()
    console.log(await readStream)
}

http.createServer((request, response) => {
    if (request.url?.[1]) {
        response.setHeader("content-type", "text/html")

        response.end(`<!doctypehtml>
            <html>
                <body>
                    <script>
                        (${abortStream})()
                    </script>
                </body>
            </html>
        `)
    } else {
        response.end(new Uint8Array(20000))
    }
}).listen(80, abortStream)
```

**Review by KhafraDev — APPROVED** [review]

**Comment by KhafraDev** [comment]
Thank you!

**Pull request merged**
