### PR TITLE
remove FileReader / FileAPI

### PR DESCRIPTION
**Pull request by KhafraDev**
removes all traces of FileReader and the remaining FileAPI parts we had.

### CODE REVIEW

**Comment by KhafraDev** [comment]
it was easier than rebasing the old pr

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by ronag** [comment]
@KhafraDev please fix conflicts

**Comment by KhafraDev** [comment]
wtf did I do

**Comment by KhafraDev** [comment]
oh the remove File PR got merged which was based on this PR so it's already been removed

**Pull request closed without merging**
