### PR TITLE
perf: optimize HeadersList.clear

### PR DESCRIPTION
**Pull request by tsctx**
## Rationale

Checking the Map size and not clearing is thirty times faster if the map is empty.

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by KhafraDev — COMMENTED** [review]
I'm all for optimizing, but when would someone ever clear an empty Headers? It seems like a case that would never happen.

**Comment by tsctx** [comment]
@KhafraDev https://github.com/nodejs/undici/pull/2454#discussion_r1404768634

**Comment by tsctx** [comment]
The headersList is empty unless the first argument of the Request constructor is Request

**Comment by tsctx** [comment]
@KhafraDev The same logic is used here.
https://github.com/nodejs/undici/blob/0437f69d186e7144e726f0657e5cda08b418606b/lib/fetch/headers.js#L230-L234

**Comment by ronag** [comment]
> @KhafraDev The same logic is used here.
> 
> https://github.com/nodejs/undici/blob/0437f69d186e7144e726f0657e5cda08b418606b/lib/fetch/headers.js#L227-L237

That's not quite the same. It avoids creating an unnecessary iterator. But yea, I would argue it's unnecessary there as well.

**Comment by tsctx** [comment]
It is the same in that it avoids unnecessary function execution.

**Comment by tsctx** [comment]
On second thought, this does not seem necessary.

**Comment by KhafraDev** [comment]
That optimization makes much more sense because headers received from the server are immutable

**Comment by tsctx** [comment]
I'm sorry. This PR thing?

**Comment by tsctx** [comment]
I'm sorry. Are you referring to this PR?

**Pull request closed without merging**
