### PR TITLE
test: add cache testing

### PR DESCRIPTION
**Pull request by tsctx**

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by KhafraDev — COMMENTED** [review]
I'm pretty sure every test here is already covered by WPTs.

**Comment by tsctx** [comment]
@KhafraDev https://github.com/nodejs/undici/pull/2612#issuecomment-1893841080

**Comment by KhafraDev** [comment]
I think Matteo meant was that a test specifically for accessing the signal was needed, not that we need to duplicate the tests

**Pull request closed without merging**
