### PR TITLE
chore: create package.json in benchmarks

### PR DESCRIPTION
**Pull request by Uzlopak**
This is highly opinionated change. It makes my node_modules folder from 330 mb to 180 mb.

### CODE REVIEW

**Review by metcoder95 — COMMENTED** [review]
kind of over the fence, don't have a strong opinion on this one

**Review by Ethan-Arrowood — APPROVED** [review]
lol this is basically what I started doing in the monorepo migration. Happy to land this now though! Easier for me

**Comment by Uzlopak** [comment]
@mcollina 
@ronag 
yes or no :)?

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by Uzlopak** [comment]
@mcollina 
We dont need to load all those packages if we dont benchmark.

Also when installing the packages we wont see security warnings when running npm ci.

It halfs the size of node_modules.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you resolve the conflicts?

**Comment by Uzlopak** [comment]
@mcollina 
done

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
