### PR TITLE
fix: complete message error

### PR DESCRIPTION
**Pull request by ronag**
Fixes: #810
Fixes: #807

It would be nice if we could make this an actual content length mismatch error but we can leave that as future work.

### CODE REVIEW

**Comment by mcollina** [comment]
CI is red :/

**Comment by ronag** [comment]
> CI is red :/

bad GitHub merge

**Comment by ronag** [comment]
CI failures I can't repro locally on my Mac :(

**Comment by ronag** [comment]
@mcollina PTAL

**Review by dnlup — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
