### PR TITLE
fix: support no servername

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/undici/issues/992#issuecomment-958358300

### CODE REVIEW

**Comment by ronag** [comment]
@deadbeef84  can you confirm whether this solves your problem?

**Comment by deadbeef84** [comment]
Yes, this solves my problem :+1:

**Review by mcollina — COMMENTED** [review]
This area is a bit sensitive so I would prefer this comes with a test

**Comment by ronag** [comment]
Unsure how to test this at the moment… @deadbeef84 ideas?

**Review by mcollina — APPROVED** [review]
lgtm not not really happy about not having tests for these bit. Maybe using some mocks?

**Comment by deadbeef84** [comment]
maybe something similar to https://github.com/nodejs/undici/blob/main/test/https.js but instead of `localhost` you use `127.0.0.1`? I just tested and that reproduces the error.

**Review by szmarczak — APPROVED** [review]

**Pull request merged**
