### PR TITLE
feat: implement `BodyReadable.bytes`

### PR DESCRIPTION
**Pull request by tsctx**
Refs: #3262

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you add it to the docs?

**Review by KhafraDev — APPROVED** [review]
as a side note we should probably add a test similar to 9134ee653af1ac933df975d76883fefd92bc23c2 to be safe

**Comment by tsctx** [comment]
@mcollina ptal

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
