### PR TITLE
fix: ignore not exists queue request on client error

### PR DESCRIPTION
**Pull request by fengmk2**
## This relates to...

closes https://github.com/nodejs/undici/issues/3857

### Bug Fixes

Ignore not exists request on queue

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Review by ronag — CHANGES_REQUESTED** [review]
I believe this just hides an underlying issue...

**Comment by fengmk2** [comment]
> Thanks for opening a PR! Can you please add a unit test?

No problem, I'll try to find out the conditions for reproduction and add unit tests

**Comment by metcoder95** [comment]
Agree with @ronag.
I believe this was already fixed with #3875

**Pull request closed without merging**
