### PR TITLE
fix: 🏷️ add allowH2 to BuildOptions

### PR DESCRIPTION
**Pull request by binsee**
## This relates to...

- #2333

### Bug Fixes

- Fix missing definition allowH2 in BuildOptions

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you add a test for this type? We use tsd.

**Comment by binsee** [comment]
> Can you add a test for this type? We use tsd.

Yes

**Comment by binsee** [comment]
@mcollina I'm not familiar with tsd, could you please check if my changes are correct?

**Review by metcoder95 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
