### PR TITLE
 test: re-enable gc test on darwin 

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/515

### CODE REVIEW

**Comment by ronag** [comment]
@dnlup

**Review by Ethan-Arrowood — APPROVED** [review]
lgtm, can you link whatever resource led to this solution? I'm interested in learning more about it

**Comment by ronag** [comment]
Unfortunately, no idea. GC behavior is magic.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by dnlup** [comment]
I am late here too, I am happy you could fix this 🙂.

**Pull request merged**
