### PR TITLE
fix missing client arg

### LINKED ISSUE #554: disconnect event missing args
https://github.com/nodejs/undici/pull/550#discussion_r577715865

> Okay I found two disconnect event instances:
> 
> https://github.com/nodejs/undici/blob/10486556f3a2c40a7e90851da7867d1868fb0027/lib/core/client.js#L493
> 
> https://github.com/nodejs/undici/blob/10486556f3a2c40a7e90851da7867d1868fb0027/lib/core/client.js#L823
> 
> One calls with `client, error` and the other just `error`. Is this okay? Should we fix the inconsistency and also return client in the later disconnect event?

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
closes #554 

doc update included in #550

### CODE REVIEW

**Comment by ronag** [comment]
Would be nice with a test. Is this the only occurance?

**Comment by Ethan-Arrowood** [comment]
Yeah only occurrence, most of the tests use neither arguments in the event listener, but there is one test that checks them: https://github.com/nodejs/undici/blob/master/test/pool.js#L39

**Comment by ronag** [comment]
In the upgrade test can you add a check for disconnect + correct args.

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Comment by Ethan-Arrowood** [comment]
Also found another test for this but its not upgrade related so this new case is a good addition

https://github.com/nodejs/undici/blob/master/test/client.js#L980

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I _think_ this is semver-major cc @ronag.

**Comment by ronag** [comment]
> I _think_ this is semver-major cc @ronag.

This is kind of a bug of a previous semver-major. I'm fine with landing as a patch if @mcollina is.

**Review by ronag — APPROVED** [review]

**Comment by ronag** [comment]
It is semver major. A fix for https://github.com/nodejs/undici/pull/544 which we haven't released,

**Pull request merged**
