### PR TITLE
refactor: simplify pause

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/681

### CODE REVIEW

**Comment by ronag** [comment]
@dnlup I tried, I saw, I failed. Do you want to try? I'm not sure I quite understand how to resume the parser.

**Comment by dnlup** [comment]
> @dnlup I tried, I saw, I failed. Do you want to try? I'm not sure I quite understand how to resume the parser.

Ok, I'll try. Yeah, it's tricky. I think Node handles everything in the `execute` function, not sure though. What is the condition triggering the pause? The client calling `pause` on the `socket`?

**Comment by ronag** [comment]
> > @dnlup I tried, I saw, I failed. Do you want to try? I'm not sure I quite understand how to resume the parser.
> 
> Ok, I'll try. Yeah, it's tricky. I think Node handles everything in the `execute` function, not sure though. What is the condition triggering the pause? The client calling `pause` on the `socket`?

The pause is triggered by the return value of `onHeader` and `onData`.

**Comment by ronag** [comment]
@dnlupI think I'm onto somthing

**Comment by ronag** [comment]
Another one bites the dust!

**Comment by ronag** [comment]
This is so much nicer.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Ethan-Arrowood — APPROVED** [review]
this looks great

**Comment by dnlup** [comment]
This is great!

**Pull request merged**
