### PR TITLE
fix issue 2898

### PR DESCRIPTION
**Pull request by KhafraDev**
This took me an hour to solve. Fuck me.

Fixes https://github.com/nodejs/undici/issues/2898

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]

**Comment by Uzlopak** [comment]
windows tests fail

**Comment by KhafraDev** [comment]
wanna help figure out why

**Comment by Uzlopak** [comment]
sure, will boot into windows

**Comment by KhafraDev** [comment]
a windows only issue that's either with the testrunner or with webstreams. a truly fun issue. I can't get it to repro w/o the test runner

**Comment by KhafraDev** [comment]
@Uzlopak minimal example, without using fetch 😒 

```mjs
const { test } = require('node:test')

function cloneBody (body) {
  // To clone a body body, run these steps:

  // https://fetch.spec.whatwg.org/#concept-body-clone

  // 1. Let « out1, out2 » be the result of teeing body’s stream.
  const [out1, out2] = body.stream.tee()
  const out2Clone = structuredClone(out2, { transfer: [out2] })
  // This, for whatever reasons, unrefs out2Clone which allows
  // the process to exit by itself.
  const [, finalClone] = out2Clone.tee()

  // 2. Set body’s stream to out1.
  body.stream = out1

  // 3. Return a body whose stream is out2 and other members are copied from body.
  return {
    stream: finalClone,
    length: body.length,
    source: body.source
  }
}

test('test', async (t) => {
  const rs = new ReadableStream({
    pull (controller) {
      controller.byobRequest?.respond(0)
    },
    type: 'bytes'
  })

  cloneBody({ stream: rs })
})

```

node --test test.js

test hangs

**Comment by Uzlopak** [comment]
If I undo your commit it works locally. If I apply your commit it hangs. Maybe the original request is not finishing. Maybe we need to keep some reference between the clones and the original and if a clone closes/finishes/ends/errors whatever, it also destroys the original request?

**Comment by KhafraDev** [comment]
its a bug in webstreams, we're basically replacing one bug for another.

**Comment by KhafraDev** [comment]
We'll just fail the tests, every other platform does anyways last I checked. We shouldn't be bothering with workarounds for bugs in node core, this issue is more important to fix.

**Comment by Uzlopak** [comment]
We patched it for wpt and that resulted in a bug in the actual tests? So we revert the change in the code so that wpt fails but the actual tests not?

**Comment by KhafraDev** [comment]
yeah

**Review by Uzlopak — APPROVED** [review]

**Review by ronag — APPROVED** [review]

**Pull request merged**
