### PR TITLE
feat: dispatcher _buildConnector() method

### PR DESCRIPTION
**Pull request by zdm**
## This relates to...

https://github.com/nodejs/undici/issues/3486

## Rationale

This patch allows to access buildConnector options in the DispatcherBase subclasses.
This will allows to create custom `connect` function in subclasses using `buiildConnector` options.

## Changes

1. `_buildConnector()` protected method added to `DispatcherBase`.
2. `buildConnector` calls changed from direct use to use `this._buildConnector()` method.
3. helper function `configureSocket()` added. It sets socket `no delay` and `keep alive` based on passed options.

### Features

It is too hard to make `connect` callback receive full list of connect options. 
At least I have no idea how to implement it on current code base without deep refactoring.
This patch helps to solve this problem in dispatcher subclasses, that will be enough for most of developers.

Use case:
```
import Client from 'undici/dispatcher/client'
import { configureSocket } from 'undici/core/connect'

export default class extends Client {

  _buildConnector (buildOptions) {

    // create custom connector
    if (this.proxy) {
      return async (options, callback) => {
        const socket = await this._createSocket(buildOptions, options)

        callback(configureSocket(socket))
      }

    // or fallback to the default behavior
    } else {
      return super._buildConnector(buildOptions)
    }
  }
}
```

### Bug Fixes

https://github.com/nodejs/undici/issues/3486
## Status

- [x ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by mcollina** [comment]
why is this needed?

**Comment by zdm** [comment]
This is needed if I want to create custom dispatcher and get access to buildConnector options (with resolved default values), please look at related issue.

**Review by ronag — CHANGES_REQUESTED** [review]
I don't think this is a good idea...

**Comment by zdm** [comment]
Why nor? Do you have arguments?
"buildConnector" is used in subclasses constructor, why not provide this standard functionality as private method?
I think this is obvious

**Pull request closed without merging**
