### PR TITLE
fix: avoid mem leak

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/node/issues/46435
Refs: https://github.com/nodejs/undici/issues/1926

### CODE REVIEW

**Comment by ronag** [comment]
@jamesdiacono @stalkerg Can you try and see if this fixes your issue?

**Comment by ronag** [comment]
If this helps it almost feels like a V8 bug.

**Comment by stalkerg** [comment]
I will try today, not so easy however in my case.

**Comment by stalkerg** [comment]
No, it's not helped me.

**Comment by stalkerg** [comment]
I think the reason is somewhere here:
```
signal.addEventListener('abort', abort, { once: true })
requestFinalizer.register(this, { signal, abort })
```

Because our `abort` function borrows `ac` object, which is bounded to `this` by `this[kSignal] = ac.signal`.

**Comment by stalkerg** [comment]
Very interesting! If I comment this `requestFinalizer.register(this, { signal, abort })` it's also help.

**Pull request closed without merging**
