### PR TITLE
remove FileReader

### PR DESCRIPTION
**Pull request by KhafraDev**

### CODE REVIEW

**Comment by KhafraDev** [comment]
When we eventually drop support for node 18, we can finally get rid of our File implementation, which means we won't have to run any FileAPI WPTs anymore!

**Comment by mcollina** [comment]
Unfortunately I don't think we can drop Node v18 anytime soon because it’ll be lts for another year.

**Comment by KhafraDev** [comment]
Of course not 😅. I was just talking about way in the future. We still have our own File.

**Comment by ronag** [comment]
Rebase to next branch?

**Comment by KhafraDev** [comment]
can we land this? 👀

**Comment by KhafraDev** [comment]
I made a PR to remove FileReader from fetch tests. This is safe to land in the meantime. https://github.com/web-platform-tests/wpt/pull/44893/

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by metcoder95 — APPROVED** [review]

**Comment by KhafraDev** [comment]
Now that we've removed our File impl. we can stop running the fileapi WPTs altogether.

**Pull request closed without merging**
