### PR TITLE
perf(headers): if the guard is immutable (forEach)

### PR DESCRIPTION
**Pull request by tsctx**
## Rationale

See #2424

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [x] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by tsctx** [comment]
cc @KhafraDev

**Review by mcollina — APPROVED** [review]
lgtm

**Review by KhafraDev — COMMENTED** [review]
iterating over `this` uses headers' entries which should already be optimized for immutable headers?

**Comment by tsctx** [comment]
@KhafraDev 
On second thought, this method has less overhead but most people use iterators, close this PR.

**Pull request closed without merging**
