### PR TITLE
fix: response error interceptor

### PR DESCRIPTION
**Pull request by Gigioliva**
# Fix response error interceptor

## Rationale

This [this issue](https://github.com/nodejs/undici/issues/3929) 

## Changes

Use the correct method signature.

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by Gigioliva** [comment]
Tests are failing for something not related to my PR 🤷🏼‍♂️ Also in main they fail

**Comment by mcollina** [comment]
Can you please rebase/update this branch?

**Review by metcoder95 — APPROVED** [review]

**Comment by Gigioliva** [comment]
> Can you please rebase/update this branch?

Done... but still there are some flaky tests

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
