### PR TITLE
fix: use normal timers for delays < 1s

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/1950

### CODE REVIEW

**Comment by ronag** [comment]
@mciocan  do you think you could add a test to this PR?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I have a feeling any tests for this would be incredibly flaky

**Comment by mciocan** [comment]
Thank you a lot 💯

**Pull request merged**
