### PR TITLE
chore: simplify creation of `fetch error`

### PR DESCRIPTION
**Pull request by fedyk**
## Simplify creation of `fetch error`

This relates to the way how `fetch error` is created. `TypeError` accept `cause` in constructor, so `Object.assign` can be removed.

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Review by metcoder95 — APPROVED** [review]

**Comment by KhafraDev** [comment]
A few things:
- this will drop support for node v16.8 (or make the error entirely useless). Not really an issue but the README should be changed.
- there's at least one more place where this pattern is used, I think in `lib/fetch/body.js`? It should be changed there also.

**Review by mcollina — CHANGES_REQUESTED** [review]
I don't think we should be landing this without bumping a major.

**Comment by metcoder95** [comment]
Changed, the branch but it seems `next` needs to be rebased

**Comment by fedyk** [comment]
@KhafraDev thanks for your comment. I've adjusted `lib/fetch/body.js` and `lib/fetch/response.js` as well.

As for changes in README, I didn't get the point with dropping support for node v16.8. If it is critical for this MR, please elaborate 🙂

**Comment by mcollina** [comment]
This commit should target the `next` branch

**Comment by KhafraDev** [comment]
> As for changes in README, I didn't get the point with dropping support for node v16.8. If it is critical for this MR, please elaborate 

error.cause was added in node v16.9, at least according to mdn. On node v16.8, which is currently supported by undici, the error message will be completely useless with this change, essentially dropping support for it IMO.

**Comment by fedyk** [comment]
> > As for changes in README, I didn't get the point with dropping support for node v16.8. If it is critical for this MR, please elaborate
> 
> error.cause was added in node v16.9, at least according to mdn. On node v16.8, which is currently supported by undici, the error message will be completely useless with this change, essentially dropping support for it IMO.

You are right - `cause` is supported since [v16.9.0](https://nodejs.org/api/errors.html#errorcause)

**Comment by fedyk** [comment]
I've created a new clean MR for the changes https://github.com/nodejs/undici/pull/2347. This one got glutted

**Pull request closed without merging**
