### PR TITLE
perf: use tree

### PR DESCRIPTION
**Pull request by tsctx**

### CODE REVIEW

**Comment by mcollina** [comment]
Can you rebase? CI should be better

**Comment by tsctx** [comment]
@mcollina I was able to fix it.

**Review by metcoder95 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

Can you rebase again? CI should be green now

**Review by KhafraDev — APPROVED** [review]
LGTM but I missed the original discussion - is converting it to a string faster than checking if the buffers are equal?

**Comment by tsctx** [comment]
@KhafraDev It is a little faster, but the difference is negligible.

**Pull request merged**
