### PR TITLE
fix: update wasi

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
@dnlup could you take a look at why this doesn't build?

```
clang-10: error: unknown argument: '-mexec-model=reactor'
```

**Comment by dnlup** [comment]
> @dnlup could you take a look at why this doesn't build?
> 
> ```
> clang-10: error: unknown argument: '-mexec-model=reactor'
> ```

I'll try to take a look at it next week 😉

**Comment by dnlup** [comment]
It seemed related to https://github.com/WebAssembly/wasi-sdk/issues/203. I used the newest version with the fix and it compiled successfully.

**Comment by ronag** [comment]
Thanks!

**Pull request merged**
