### PR TITLE
Do not decode the body while we are following a redirect

### PR DESCRIPTION
**Pull request by mcollina**
Ref: https://github.com/nodejs/node/issues/43868

Signed-off-by: Matteo Collina <hello@matteocollina.com>

### CODE REVIEW

**Review by ronag — APPROVED** [review]
I still don't think this fixes the missing error handler. I don't understand how it became unhandled.

**Comment by mcollina** [comment]
> I still don't think this fixes the missing error handler. 

It doesn't. That's a node core bug from my point of view.

This "hotfix" removes the decoding of a body that's not going to be decoded anyway.

This originates from https://github.com/nodejs/undici/blob/26f60b7b6e612bb831133d7f85914963d1955011/lib/fetch/index.js#L1053-L1057.. it's the old https://github.com/whatwg/fetch/issues/1288.

**Comment by mcollina** [comment]
I think it's https://github.com/nodejs/node/pull/41954, specifically https://github.com/nodejs/node/pull/41954/files#diff-95c23fb6674af85f6f23a374851af6cccf58fb4617d73897df5078ba537a862cR243. We are not consuming that decoded stream completely. Therefore we are crashing.

This fix looks correct now.

**Comment by ronag** [comment]
I feel there is a more fundamental problem here but this should fix the most immediate issue.

**Pull request merged**
