### PR TITLE
remove autobahn reports from gitignore

### PR DESCRIPTION
**Pull request by KhafraDev**
part of #3312

### CODE REVIEW

**Comment by tsctx** [comment]
json may not be necessary

**Review by tsctx — APPROVED** [review]
lgtm

**Comment by KhafraDev** [comment]
it's not necessary for the report but could be useful for detecting test result changes

**Review by tsctx — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
I'm -1. These are over 1000 files with a total of 353468 lines. If we kept updating them, they would engulf our github repository. We need a different strategy for this.

I didn't expect the autobahn report to be this big. Is there a summary possible?

**Comment by KhafraDev** [comment]
They won't need to be updated much - the tests are already passing. If we remove all of the html/json files other than index.html we lose out on any benefit of publishing it.

**Comment by mcollina** [comment]
@ronag @Ethan-Arrowood have you got a solution for this?

**Pull request closed without merging**
