### PR TITLE
handle maxCachedSessions option in connect class

### PR DESCRIPTION
**Pull request by KiraPC**
Issue: https://github.com/nodejs/undici/issues/783

As per the issue description I've added the implementation to handle the maxCachedSessions option, inspired by the node http.Agent.

I would like to discuss about how I handled the default and the zero value.

- Is it ok to set the default to 100 as node does in its Agent?
- Is it ok to disable the session reusability if the value of this option is zero, even if you can disable it reuseSessions option?

Thanks.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add docs?

How does Node.js behave when the option is set to zero?

**Comment by KiraPC** [comment]
@mcollina Yes, sure, I'll docs asap.

node Agent disable the caching too (I was inspired by them).

My question is, do we should handle the option reuseSessions if the behavior is the same?

**Review by ronag — CHANGES_REQUESTED** [review]
I don’t think the extra list is necessary.

**Comment by mcollina** [comment]
I think we should just remove reuseSessions.

**Comment by KiraPC** [comment]
> I don’t think the extra list is necessary.

Hi, 

I introduced that list to remove the oldest session. So, if the cached sessions are more then configured, I get the first session cached and remove it from the map.

How can I do the same thing with just the Map object?

**Comment by ronag** [comment]
> > I don’t think the extra list is necessary.
> 
> Hi,
> 
> I introduced that list to remove the oldest session. So, if the cached sessions are more then configured, I get the first session cached and remove it from the map.
> 
> How can I do the same thing with just the Map object?

Create an iterator and call next()

**Comment by KiraPC** [comment]
@mcollina Added docs and types and removed reuseSessions (this last was never documented, so I just removed it from code).

@ronag Done with map.keys, thanks for the suggestion.

I also moved the option out from tls option object because [tls.options](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) doesn't include it.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
