### PR TITLE
Add all properties is v3 esm wrapper

### PR DESCRIPTION
**Pull request by mcollina**
closes #765

### CODE REVIEW

**Comment by mcollina** [comment]
cc @RafaelGSS

**Review by ronag — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
Just a note, I've tested using the `main` branch directly instead of the latest release (3.3.5) and is working fine already.

However, I think that this PR should land too.

**Comment by mcollina** [comment]
this is mainly targeting v3

**Comment by mcollina** [comment]
(mac build was stuck, landing and releasing)

**Pull request merged**
