### PR TITLE
abort request with reason if one is provided

### LINKED ISSUE #2590: request throws `AbortError` rather than `TimeoutError` when passed AbortSignal.timeout(1000) as signal
## Bug Description
```
AbortError: Request aborted
    at abort (file:///D:/0/lib/deps.bundle.js:19008:18)
    at self.<computed> (file:///D:/0/lib/deps.bundle.js:19027:5)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at EventTarget.dispatchEvent (node:internal/event_target:757:26)
    at abortSignal (node:internal/abort_controller:374:10)
    at Timeout._onTimeout (node:internal/abort_controller:128:7)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

## Reproducible By
import { request } from 'undici'

await request('http://localhost', { signal: AbortSignal.timeout(1000) })

## Expected Behavior

```
TimeoutError: xxx
```

## Logs & Screenshots

image

## Environment

latest node.js
latest windows

### PR DESCRIPTION
**Pull request by KhafraDev**
fixes #2590

### CODE REVIEW

**Comment by KhafraDev** [comment]
might be a major change, marking it as such just to be safe

**Comment by mcollina** [comment]
I don't think this is a major change.

**Review by ronag — APPROVED** [review]

**Comment by KhafraDev** [comment]
hopefully a flaky test?

```
 not ok 2 - test/ca-fingerprint.js # time=515.802ms
  ---
  env: {}
  file: test/ca-fingerprint.js
  timeout: 60000
  command: C:\hostedtoolcache\windows\node\18.19.0\x64\node.exe
  args:
    - --expose-gc
    - test/ca-fingerprint.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\a\undici\undici
  exitCode: null
  signal: SIGTERM
  ...
```

**Comment by KhafraDev** [comment]
I'm not sure if it's a major change, it does change the errors you get when a reason isn't passed to abort. We made this change/fix in fetch when it was still experimental.

**Review by metcoder95 — APPROVED** [review]
I'm a little bit over the fence, but I believe it can pass under a `minor`.
I don't see we are breaking contracts with current usage, in any case we are extending it as we are adding now the reason if exists, otherwise we fallback to the `RequestAbortedError` which they must handle already

**Pull request merged**
