### PR TITLE
Use data event to consume body

### LINKED ISSUE #2639: Large body is truncated
If I make a second request before awaiting for the first request large body, it looks like it truncates the large body. Maybe I'm doing something wrong.

```js

'use strict'

const { createServer } = require('http')
const { request } = require('undici')

const LARGE_BODY = 'x'.repeat(10000000)

async function run () {
  // Works fine
  // const fooRes = await request('http://localhost:3000/foo')
  // const fooBody = await fooRes.body.text()

  // const barRes = await request('http://localhost:3000/bar')
  // await barRes.body.text()

  // Fails with:
  const fooRes = await request('http://localhost:3000/foo')
  const barRes = await request('http://localhost:3000/bar')

  const fooBody = await fooRes.body.text()
  await barRes.body.text()

  if (fooBody !== LARGE_BODY) {
    const contentLength = fooRes.headers['content-length']
    console.log('content length:', contentLength)
    console.log('received body length:', fooBody.length)
    console.log('expected body length:', LARGE_BODY.length)
    return
  }
  console.log('done')
}

const server = createServer((req, res) => {
  if (req.url === '/foo') {
    res.end(LARGE_BODY)
    return
  }
  if (req.url === '/bar') {
    res.end('bar')
    return
  }
  throw new Error('Unexpected request url: ' + req.url)
})

server.listen(3000, async () => {
  await run()
  process.exit(0)
})
```

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #2639

### CODE REVIEW

**Review by ronag — CHANGES_REQUESTED** [review]
This doesn't look right. I'm sick atm. Not sure if I will have energy to look into before weekend.

**Comment by mcollina** [comment]
Why? The code was very odd before, it bypassed all internal stream buffering before, and it's passing all our tests.

**Comment by ronag** [comment]
> Why? The code was very odd before, it bypassed all internal stream buffering before, and it's passing all our tests.

The point of the code is to bypass the stream logic to improve performance. If we don't want that then I believe the code can be significantly simplified.

**Comment by mcollina** [comment]
Well, I guess that code was missing some handling of an edge case because it was truncating some data in the condition included in the test.

I can try to take a look if a fix that preserve the fast path could be done.

**Pull request closed without merging**
