### PR TITLE
perf: try to re-use timer when possible

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by ronag** [comment]
branch

```
[1] http - no agent  x 3,228 ops/sec ±5.33% (78 runs sampled)
[1] http - keepalive x 675 ops/sec ±1.20% (79 runs sampled)
[1] http - keepalive - multiple sockets x 4,564 ops/sec ±1.32% (82 runs sampled)
[1] undici - pipeline x 5,355 ops/sec ±2.71% (82 runs sampled)
[1] undici - request x 6,051 ops/sec ±1.92% (82 runs sampled)
[1] undici - pool - request - multiple sockets x 6,144 ops/sec ±1.13% (82 runs sampled)
[1] undici - stream x 6,289 ops/sec ±1.57% (84 runs sampled)
[1] undici - dispatch x 6,770 ops/sec ±0.76% (83 runs sampled)
[1] undici - noop x 6,857 ops/sec ±0.68% (87 runs sampled)
[1] node -e 'setTimeout(() => {}, 1000)' && node benchmarks exited with code 0
```

current
```
[1] http - no agent  x 2,877 ops/sec ±6.53% (75 runs sampled)
[1] http - keepalive x 660 ops/sec ±1.48% (77 runs sampled)
[1] http - keepalive - multiple sockets x 4,153 ops/sec ±1.87% (79 runs sampled)
[1] undici - pipeline x 4,850 ops/sec ±4.32% (77 runs sampled)
[1] undici - request x 5,783 ops/sec ±2.10% (82 runs sampled)
[1] undici - pool - request - multiple sockets x 5,789 ops/sec ±1.35% (81 runs sampled)
[1] undici - stream x 6,096 ops/sec ±2.09% (82 runs sampled)
[1] undici - dispatch x 6,515 ops/sec ±0.94% (84 runs sampled)
[1] undici - noop x 6,658 ops/sec ±0.88% (85 runs sampled)
```

**Comment by ronag** [comment]
Interestingly enough the perf gain is negligable. Even though clinic flame blames setTimeout.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
How does the before/after flamegraph look like?

**Comment by ronag** [comment]
> How does the before/after flamegraph look like?

What's the best way to share that?

**Comment by mcollina** [comment]
zip them and attach them to the issue

**Comment by ronag** [comment]
Posting clinic data soon. But now I think this PR makes sense regardless whether it improves perf or not.

**Comment by ronag** [comment]
[Archive.zip](https://github.com/nodejs/undici/files/6299964/Archive.zip)

70439 main
68510 pr

@mcollina

**Review by dnlup — APPROVED** [review]

**Pull request merged**
