### PR TITLE
Initialize some fetch tests

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Worked on #926 but with all of the spec related changes, most of my previous tests were broken. Headers class mostly worked so I included those, but request response and body were just a mess. Probably best to start over with the new implementations.

I've stubbed those out so other contributors know where the tests need to go and such

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Why is tap failing on previous Node versions? Do we not export the fetch api or something?

**Comment by ronag** [comment]
We don't run fetch tests on node <16

**Comment by Ethan-Arrowood** [comment]
i'll add a skip to these tests then

**Comment by ronag** [comment]
https://github.com/nodejs/undici/blob/main/test/client-fetch.js#L9

**Comment by Ethan-Arrowood** [comment]
ahh i did it with the script thing and some npm scripts. Do you have a preference?

**Pull request merged**
