### PR TITLE
fix: use wasm instance map

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/undici/issues/741

### CODE REVIEW

**Comment by ronag** [comment]
Need to consider benchmarks.

**Comment by ronag** [comment]
Base on the CI benchmarks I can't see any detectable performance diff.

**Review by dnlup — APPROVED** [review]

**Comment by szmarczak** [comment]
I don't think this makes a difference in regards to the issue.

You could achieve the same just by storing the pointer and reassuring that `p` is the same as `ptr`.
If `llhttp` doesn't do anything asynchronously, that should be always the case.

**Comment by ronag** [comment]
> I don't think this makes a difference in regards to the issue.
> 
> You could achieve the same just by storing the pointer and reassuring that `p` is the same as `parser.ptr`.
> If `llhttp` doesn't do anything asynchronously, that should be always the case.

Good point. I could just add assertions.

**Pull request closed without merging**
