### PR TITLE
feat(File): proper webidl checks

### PR DESCRIPTION
**Pull request by KhafraDev**
Makes `File` completely spec-compliant and adds in a bunch of needed webidl checks.

# File:
- Fixes 0 arguments being allowed in File constructor.
- Add webidl checks for File constructor parameters.
- Add missing steps from the spec.

# WebIdl:
- Add `sequence` converters
- Add dictionary matching & optional key assigning with default & required keys.
- Add TypedArray, (Shared)ArrayBuffer, DataView, and IDL long long converters (required by File).

p.s. most of the webidl apis were inspired by Deno because they're just done well.

### CODE REVIEW

**Comment by KhafraDev** [comment]
I'm unsure what the `FileLike` class' purpose is so I haven't changed it. Should it be removed? The few instances of it throughout the code doesn't make it seem necessary, but I'm guessing there's a reason it was implemented that I don't know of.

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by jimmywarting** [comment]
I don't know who created file like class. But I think File like class was created to allow for 3th party Blob that isn't a instance of NodeJS blobs (like fetch-blob). has a feature to get Blob/Files from the file system without reading anything into memory.   Only when you call any of the read methods on the Blob will it actually read the file.
This is necessary to allow for uploading large files with eg FormData

I'm still very much missing the feature from nodejs to retrieve a Blob/File backed up by the file system. And that is one of the main issue why i simply can not extend NodeJS blobs and why fetch-blob is still necessary to this day. Without it blobs are pretty useless you might as well use arraybuffer

Blobs main purpose is to offload data to the FS

NodeJS Blob is pretty bad written in comparison to fetch-blob when it comes to streaming and creating text of blobs that are above 500mb. I have created issue about it but it haven't been resolved for a long time now.

I really want to depreciate fetch-blob but i can't until my issues on nodejs have been resolved

**Comment by ronag** [comment]
I second everything @jimmywarting. I'm the one that added `FileLike`.

**Comment by jimmywarting** [comment]
A File is more like a file handle/reference point to where the data is located with an offset and size property of where it should start reading from and where it should stop

**Pull request merged**
