### PR TITLE
Add BodyTimeoutError to error types

### PR DESCRIPTION
**Pull request by penx**
Add BodyTimeoutError to error types

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a test for the new type: https://github.com/nodejs/undici/blob/master/test/types/errors.test-d.ts?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Ethan-Arrowood — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
@ronag would you mind if I backport this to the v3.x line as v3.3.2?

**Pull request merged**
