### PR TITLE
fix(types): add missing `cache` prop to RequestInit

### PR DESCRIPTION
**Pull request by rindeal**
Also sort the props.

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [x] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by eXhumer** [comment]
Lint issues, 4 spaces instead of 2.

I don't think `undici.fetch` supports caching yet (See #2760).

If you want to implement some sort of in-memory caching, see https://github.com/nodejs/undici/issues/2760#issuecomment-1944119404.

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you add some type tests for this? We use `tsd`.

**Review by Uzlopak — CHANGES_REQUESTED** [review]
And tomorrow somebody argues, that because the cache field is in the types, we need to implement asap caching.

**Review by Uzlopak — APPROVED** [review]
@KhafraDev 

image

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
