### PR TITLE
feat!: upgrade llhttp to 9.2.0 (#2705)

### PR DESCRIPTION
**Pull request by metcoder95**
* upgrade llhttp

* fix tests

* set version of llhttp 9.2.0

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by Uzlopak** [comment]
Doesnt next already contain 9.2.0

**Review by ronag — APPROVED** [review]

**Comment by mcollina** [comment]
We should really just merge next into main.

**Comment by ronag** [comment]
> We should really just merge next into main.

We tried. The merge looks super weird. Next branch only contains 2 PRs we need.

**Comment by metcoder95** [comment]
> > We should really just merge next into main.
> 
> We tried. The merge looks super weird. Next branch only contains 2 PRs we need.

It contains too many conflicts that might be hard to solve, overall only the two PRs listed here are the ones we need to land on `main`.

**Pull request merged**
