### PR TITLE
fix: lazy decode body

### PR DESCRIPTION
**Pull request by ronag**
Don't start prefetching the body before headers and status
has been processed.

Fixes: https://github.com/nodejs/undici/issues/1271

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Comment by ronag** [comment]
@minas90 Would you mind helping with a test?

**Comment by ronag** [comment]
Maybe @KhafraDev can help with test?

**Comment by KhafraDev** [comment]
I couldn't replicate the issue

**Pull request merged**
