### PR TITLE
fix: ProxyAgent causes request.headers.host to be forcibly reset

### PR DESCRIPTION
**Pull request by 1zilc**
## This relates to...
Closes https://github.com/nodejs/undici/issues/3019

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by ronag — COMMENTED** [review]
Can we have a test?

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by 1zilc** [comment]
Unit tests have been added

**Comment by 1zilc** [comment]
I've noticed that ProxyAgent will also add ports to the host by default, which also seems to be a bug.👀

**Review by metcoder95 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
