### PR TITLE
fix: pass down context in onConnect

### PR DESCRIPTION
**Pull request by DTrombett**
## This relates to...

The retry and cache handlers do not pass down the context of the `onConnect` method. This means that using the redirect handler with one of them will not pass the context to the main handler:

```js
request("http://github.com", {
    dispatcher: new Agent().compose(
        interceptors.redirect({ maxRedirections: 1 }),
        interceptors.retry(),
    ),
}).then((res) => console.log(res.context)); // undefined

request("http://github.com", {
    dispatcher: new Agent().compose(
        interceptors.redirect({ maxRedirections: 1 }),
    ),
}).then((res) => console.log(res.context)) // { history: [URL, URL] }
```

## Changes

- Cache handler: used `...args` to pass all the args (like in the decorator handler)
- Retry handler: `onConnect` is now called on the first connection instead that in the constructor, allowing to pass the context

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [x] Review ready
- [x] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Review by ronag — APPROVED** [review]

**Comment by Uzlopak** [comment]
...args is imho not that nice. i think it does not cover in the types or so, that it can have two arguments. only abort.

**Comment by DTrombett** [comment]
I noticed that `...args` is what is used in the decorator handler too, so I assumed it would be ok

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
