### PR TITLE
fix: readable.setEncoding

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/1125#issuecomment-987724800

### CODE REVIEW

**Comment by ronag** [comment]
@koh110 Would you mind fixing tests?

**Comment by koh110** [comment]
@ronag Thanks for your PR. Here is my test code.
Would you review it?
https://github.com/nodejs/undici/pull/1131

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ronag** [comment]
Fixing this is very complicated unfortunately... :/

**Comment by koh110** [comment]
@ronag @mcollina Hi. I tried fixing this bug.
But I'm not sure if I've fixed it perfectly.
Would you review it?
https://github.com/nodejs/undici/pull/1133

**Pull request closed without merging**
