### PR TITLE
feat!: enable H2 by default

### LINKED ISSUE #2750: `fetch` support for HTTP/2 by default
### What is the problem this feature will solve?

This will get node's implementation of `fetch` closer to how it behaves in the browser.

### What is the feature you are proposing to solve the problem?

Support protocol upgrade similar to how `fetch-h2` package does. It's weird to try to use a third-party package that uses node's internal http2 package under the hood.

### What alternatives have you considered?

I am now using `fetch-h2` package, but much like `got-fetch` or `node-fetch` I fear it will fall out of spec and not evolve with the ecosystem.

### PR DESCRIPTION
**Pull request by metcoder95**
## This relates to...

Closes #2750 

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [x] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by ronag — CHANGES_REQUESTED** [review]
I'm strongly against this. I think HTTP2 for most cases is worse both in terms of performance and stability. I'm not a big fan of the quality and lack of maintenance of the http2 module in node core. I would like to even further decouple the http2 stuff from undici core. I would be happy to reconsider this position if and when James's http/3 and quic stuff lands.

**Comment by ronag** [comment]
I would suggest we enable it by default for fetch. It's slow anyway :).

**Comment by metcoder95** [comment]
I believe that most of the inquiries come from `fetch`, so I am happy to scope it for it only 🙂

**Review by mcollina — CHANGES_REQUESTED** [review]
I'm -1 with this implementation.

I think a better approach would be to enable it _only_ if the server does not advertise HTTP/1.1 in TLS. In other terms, if a server is only exposed via HTTP/2, we can support it.

**Comment by mcollina** [comment]
I think we are not ready for turning this on for all requests, there are bugs: https://github.com/nodejs/undici/issues/2801.

**Comment by metcoder95** [comment]
SGTM, let's take this back and circle once we feel we are more prepared to it; I'll revisit the bug and seek for support and possible add a fix there 👍

**Pull request closed without merging**
