### PR TITLE
fix: use separate web assembly instance for every Client

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/undici/issues/682
Refs: https://github.com/nodejs/undici/issues/659

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, I think this should fix all problems

**Comment by dnlup** [comment]
@ronag are you able to test this in the environment that is affected by #659 before merging?

**Comment by ronag** [comment]
> @ronag are you able to test this in the environment that is affected by #659 before merging?

Not really. They were not too happy about me using that environment for testing.

I think this makes sense either way, i.e. from a security standpoint different request payloads can't corrupt eachother's memory due to various bugs.

**Comment by dnlup** [comment]
> > @ronag are you able to test this in the environment that is affected by #659 before merging?
> 
> Not really. They were not too happy about me using that environment for testing.
> 
> I think this makes sense either way, i.e. from a security standpoint different request payloads can't corrupt eachother's memory due to various bugs.

Yeah, that makes sense either way. You're right.

Sorry for causing this mess. And thank you for helping in debugging this issue.

**Comment by ronag** [comment]
> Sorry for causing this mess. And thank you for helping in debugging this issue.

Don't be sorry! Quite the opposite. I very much appreciate everything you have helped with.

**Review by dnlup — APPROVED** [review]

**Pull request merged**
