### PR TITLE
update llhttp to the latest version v8.1.0

### PR DESCRIPTION
**Pull request by HassanBahati**
This pr addresses #1710 

- [x]  Extract files from [https://github.com/nodejs/llhttp/releases/tag/release%2Fv8.1.0](https://github.com/nodejs/llhttp/releases/tag/release%2Fv8.1.0)
- [x]  Replace `deps/llhttp/src` and `deps/llhttp/include` with those from [https://github.com/nodejs/llhttp/releases/tag/release%2Fv8.1.0](https://github.com/nodejs/llhttp/releases/tag/release%2Fv8.1.0)
- [x]  Run `npm run prebuild:wasm`
- [x] Run `npm run build:wasm`

### CODE REVIEW

**Comment by HassanBahati** [comment]
@mcollina please review

**Comment by mcollina** [comment]
Please update the llhttp wasm bundle

**Comment by HassanBahati** [comment]
> 

Okay please, let me do so

**Comment by HassanBahati** [comment]
> Please update the llhttp wasm bundle

@mcollina , I've tried with different versions of Node.js and also tried various solutions online, but this error hinders me from updating the llhttp wasm bundle when i run `npm run prebuild:wasm`

Even with the latest version `v19.0.0` of Node.js , still unable to successfully run `npm run prebuild:wasm`




Screenshot from 2022-10-20 20-50-01

**Comment by mcollina** [comment]
You have a broken node/npm installation. You have likely installed node via brew/apt/* at some time and never removed it. On top, the nvm paths are misconfigured.

**Comment by HassanBahati** [comment]
@mcollina thank you for the feedback, on reinstalling node.js all worked fine. I have updated the wasm bundle

**Comment by mcollina** [comment]
Please run `npx standard --fix` to adjust linting.

**Comment by HassanBahati** [comment]
> 

Okay please, let me do so

**Comment by HassanBahati** [comment]
@mcollina i fixed the linting

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
