### PR TITLE
test: first attempt for flaky fix

### LINKED ISSUE #2321: test: Flaky test for Fetch + HTTP/2
## Bug Description

The following test is unstable and fails from time to time; it requires further research on how to handle it better. An initial guest is a possible race condition but it requires further investigation.

https://github.com/nodejs/undici/blob/e5c9d703e63cd5ad691b8ce26e3f9a81c598f2e3/test/fetch/http2.js#L177

## Reproducible By

- Any PR, often on v20 tests

## Logs & Screenshots

```shell
    # Subtest: [Fetch] Should handle h2 request with body (stream)
        1..8
        ok 1 - should be equal
        ok 2 - should be equal
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equal
        ok 6 - should be equal
        ok 7 - should be equal
        not ok 8 - should be equal
```

## Environment

- Often v20.

### PR DESCRIPTION
**Pull request by metcoder95**
## This relates to...

Fixes #2321

## Rationale

A race condition seems to happen between the server response and the assertion for it few lines after. This is a very rare condition, but it happens. This PR fixes it by waiting for the response to be fully read before asserting it.

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by metcoder95** [comment]
It seems to solve the issue, but running the whole suite once more to verify

**Comment by mcollina** [comment]
Windows seems to be failing still

**Comment by KhafraDev** [comment]
windows is failing on the WPTs for `The syntax of the command is incorrect.`...

**Comment by metcoder95** [comment]
Tests seem stable, failures are either redirect, windows WPTs, and now npm `ECONNRESET`

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
