### PR TITLE
enforce latin-1 encoding in source

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Related to: https://github.com/nodejs/node/pull/51605

this replaces all `’` with `'` and the `ä` with `a` in a licensing comment.

Based on my research, the licensing comment change does not impact its validity. It would actually be more appropriate to have a complete License file along with the code instead of having it inlined.  

I also tried out the `--minify-whitespace` flag for esbuild. This would remove comments from `node:build`, but also remove all other whitespace. There does not seem to be an esbuild configuration option that only removes comments. We could consider another tool for that so we can retain other whitespace.

### CODE REVIEW

**Review by KhafraDev — DISMISSED** [review]
> If we remove those comments it'll make debugging fetch 10x harder.

We can no longer copy and paste these comments and find where they originate from in the spec (I do this frequently when updating the impl. or fixing bugs). Since esbuild should be removing comments, it's likely a bug there. We can alternatively add a post processing script that strips these only in the bundled file.

I'm very much a -1 against this change. It'll make maintaining fetch harder for little benefit.

**Comment by Ethan-Arrowood** [comment]
Not a bug in esbuild: https://github.com/evanw/esbuild/issues/3117#issuecomment-1550565092

**Comment by Ethan-Arrowood** [comment]
Just tried it and changing the character has no effect on search/find on the spec 😄

**Comment by Ethan-Arrowood** [comment]
But I hear you. I agree too. I think this is an unnecessary change. I think we should minify the build and use source maps for proper stack traces. Not sure how Node.js internal deps handles that so I have to look into it further.

**Comment by KhafraDev** [comment]
Internal deps are kinda a nightmare: they get their own version of require that doesn't work well with multiple files (which is why undici is bundled unfortunately).

**Comment by KhafraDev** [comment]
The issue with the require we get there is that it only prepends 'internal' to the path, which means we'd have to replace every require in undici with `require('undici' + oldPath)` (which then gets resolved to `internal + undici + oldPath` which should theoretically work?). I did look into it a while back, when we had the --keep-names issue with the bundle, but quickly found out it was definitely the correct answer.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by KhafraDev** [comment]
@Ethan-Arrowood I made an alternate PR that strips the comments from the node build only.

**Comment by joyeecheung** [comment]
> they get their own version of require that doesn't work well with multiple files (which is why undici is bundled unfortunately).

I am pretty sure that can be special cased for undici, though I am not sure what undici uses as module id if not unbundled. The internal require will always be just minimal so nothing fancy like module path monkey patching would ever be supported, but prepending certain prefixes when the request comes from under `internal/deps/undici` wouldn't be that hard.

**Comment by mcollina** [comment]
@Ethan-Arrowood @KhafraDev what's the status of this? There are conflicts now.

**Comment by Ethan-Arrowood** [comment]
I think @KhafraDev preferred another methodology. Since he's modifying this source more than I am these days, I'm okay deferring to his preference 😄

**Pull request closed without merging**
