### PR TITLE
test: fix Fetch/HTTP2 tests

### PR DESCRIPTION
**Pull request by metcoder95**
## This relates to...

- HTTP2 support on Undici

### Bug Fixes

- Possible flaky tests for H2

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by metcoder95** [comment]
I believe we have a small bug on Node for the streams. For v16, although it is in the docs, the `Redeable.toWeb` is missing, but not on v18 nor v20 (those failures are due to the `redirect-request` tests).

On v16.20:
```shell
 stream [Function: Readable] {
	ReadableState: [Function: ReadableState],
   _fromList: [Function: fromList],
   from: [Function (anonymous)],
   wrap: [Function (anonymous)]
 }
```

>v18

```shell
stream [Function: Readable] {
   ReadableState: [Function: ReadableState],
   _fromList: [Function: fromList],
   from: [Function (anonymous)],
   fromWeb: [Function (anonymous)],
   toWeb: [Function (anonymous)],
   wrap: [Function (anonymous)]
 }
```

**Comment by metcoder95** [comment]
cc @mcollina @ronag

**Comment by mcollina** [comment]
Can you fix the v16 problem?

**Comment by metcoder95** [comment]
Sure, do you refer to check on Node and possibly open a PR?
The only issue with the tests is that Node v16 does not exposes `Redeable.toWeb` although it says so in the docs

**Comment by mcollina** [comment]
CI fails on Node v16. It should not.

**Comment by metcoder95** [comment]
Should I `skip` the test on v16?

**Comment by KhafraDev** [comment]
Yes

**Comment by mcollina** [comment]
v16 is still failing

**Comment by metcoder95** [comment]
It failed due to redirect-request: https://github.com/nodejs/undici/actions/runs/6195437501/job/16820155843?pr=2263#step:14:10764

We have #2259 for that. I might look at that on this afterwards.

Retried the CI to see if solves by itself

**Comment by KhafraDev** [comment]
we could split redirect-request into multiple files to help narrow down which test is failing, we did it for the fetch abort tests and it made debugging them much easier

**Comment by metcoder95** [comment]
I'm starting to believe that the fact we were running the CI twice per pr was causing some inconsistencies while running the tests. Now everything seems green, including v20 🤔

**Review by KhafraDev — APPROVED** [review]
I hope it was that easy

**Pull request merged**
