### PR TITLE
fix: transfer nullish coalescing assignment(??=) syntax(#2117)

### LINKED ISSUE #2117: nullish coalescing assignment(??=) is not support in node 14
## Bug Description

nullish coalescing assignment(??=) is not support in node 14, but undici require a node version >= 14

## Reproducible By

image

## Expected Behavior

not throw error in node 14

## Logs & Screenshots

image

## Environment

Node v14.21.3
MacOS 13.3.1 (a) (22E772610a)

### Additional context

no

### PR DESCRIPTION
**Pull request by quanru**
close #2117

### CODE REVIEW

**Comment by KhafraDev** [comment]
Can you add a test? These shouldn't be exported in node 14.

**Review by ronag — CHANGES_REQUESTED** [review]
Node 14 is EOL. We have dropped support.

**Comment by quanru** [comment]
> Node 14 is EOL. We have dropped support.

I found engines described in package.json is ">= 14": https://github.com/nodejs/undici/blob/9d30456aa6f195b83ea4ba36ed0b51a951e6bd87/package.json#L107

**Comment by Uzlopak** [comment]
@ronag 
We can close this as engines in package.json is now set to >= 18.

**Pull request closed without merging**
