### PR TITLE
refactor!: drop interceptors

### PR DESCRIPTION
**Pull request by metcoder95**
- **refactor(#2722)!: Drop Interceptors support (#2754)**
- **fix: tweaks**

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Comment by metcoder95** [comment]
I'm finding quite more hidden testing situations that might need to be sorted out; the cherry-pick sadly was not completely clean.

**Comment by ronag** [comment]
I don't think it's a lot of work to just re do it from beginning?

**Comment by metcoder95** [comment]
There are a few tests that will be interesting to migrate to the new interceptor setup, but those will take more time so I'd skip them from now.

But the cherry-pick didn't work as I expected, so I'll do it manually instead

**Comment by metcoder95** [comment]
Will create a new one from scratch, the cherry-pick on this one went out of hand

**Pull request closed without merging**
