### PR TITLE
perf: keep headers as Buffer

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/undici/issues/590

### CODE REVIEW

**Review by Ethan-Arrowood — APPROVED** [review]
i like this change; and I think in the future we can align more with the headers class/utilities from undici-fetch.

Maybe an undici-headers repo is in order 😋

**Comment by mcollina** [comment]
Does this improve perf? Have you got metrics?

**Comment by ronag** [comment]
See the benchmark ci

**Comment by mcollina** [comment]
There does not seem to be any benefit.

**Comment by ronag** [comment]
It’s negligible. I have some future zero copy optimizations in mind.

Maybe also useful when proxying.

I’ll see if I can find a better motivation for this change.

**Comment by mcollina** [comment]
I'm not blocking it

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
