### PR TITLE
fix: forward dispatch return value

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/undici/discussions/3373
Refs: https://github.com/nodejs/undici/issues/3370

### CODE REVIEW

**Comment by ronag** [comment]
Things this doesn't solve.

- async dispatch 
- drain event parameters (which you could argue are useless)

**Review by metcoder95 — COMMENTED** [review]
It has sense; I just feel that this can cause the false sensation of having a fully fledge `dispatcher`.

It might be possible that we end with max listeners problems.

Shall we tests the events are emitted as we expect?

**Comment by ronag** [comment]
I feel this is just a hack until we have a better solution.

**Comment by ronag** [comment]
We would need to have some form of weak event listeners for this to work well.

**Comment by ronag** [comment]
@benjamingr Do you have any input on how we can have weak event listeners here that when the `ComposedDispatcher` is gc:d will be freed?

**Comment by ronag** [comment]
This is still not great though... until GC the event listeners are still registered.

**Comment by ronag** [comment]
The alternative is that we have some kind of ref/unref API. But that is going to be a constant pain of people doing it wrong.

**Comment by ronag** [comment]
Also noticed that `Agent.dispatch` doesn't forward return value.

**Comment by benjamingr** [comment]
> @benjamingr Do you have any input on how we can have weak event listeners here that when the ComposedDispatcher is gc:d will be freed?

We don't currently expose it but you can use kWeakHandler in the version bundled with Node, that lets you pass a listener and an object that the listener's lifetime is bound to - that's EventTarget though.

So we would need to build kWeakHandler (or similar) to EventEmitter and expose that to undici somehow - it has to be baked into the abstraction (EventEmitter) itself - otherwise it leaks the WeakRef itself (as you probably noticed).

**Comment by ronag** [comment]
@metcoder95 @mcollina wdyt of returning a `Proxy`?

**Comment by metcoder95** [comment]
>So we would need to build kWeakHandler (or similar) to EventEmitter and expose that to undici somehow

This sounds great, but personally I'm afraid we will be attaching `undici` to Node internals and userland usage might suffer from a workaround that does not behaves the same.
It would be nice to have something we can use in the form of a public API for that

>wdyt of returning a Proxy?

It simplifies a lot certainly, how does the gc behave (out of curiosity mostly)?

**Comment by ronag** [comment]
> how does the gc behave (out of curiosity mostly)?

We cannot say anything about gc behavior other than it probably runs every now and then.

**Review by metcoder95 — APPROVED** [review]

**Pull request merged**
