### PR TITLE
test: Added test for RedirectHandler upgrade handling.

### PR DESCRIPTION
**Pull request by ShogunPanda**
This covers `undici.upgrade` use case when using `maxRedirections`, as requested in #438.

### CODE REVIEW

**Comment by ronag** [comment]
Do we need a test for redirecting to an upgrade? i.e. upgrade **after** redirect?

**Comment by ShogunPanda** [comment]
Very good point. Let me refactor so it tests both at once!

**Comment by ronag** [comment]
Maybe we should land this with docs and typedefs **after** @Ethan-Arrowood has done his iteration. I kind of told him that there would be no further API changes 😄 .

**Comment by ShogunPanda** [comment]
@ronag I've update the test and found out that upgrade was not working with redirect. I was eventually able to fix it but I'd like to have your opinion.

**Comment by ronag** [comment]
I think the test is flawed. The server should not upgrade the connection if the user hasn't asked for it.

What you should do here is add tests for `undici.upgrade` and `undici.connect` where the server redirects.

**Comment by ronag** [comment]
Another option is that we simply don't support redirect + upgrade for now. Which IMO is unfortunate but acceptable.

**Comment by ShogunPanda** [comment]
Well, the client is using upgrade. So it implicitily asked for Upgrade to undici and thus to the server. And since maxRedirections are not zeroed, we also have to handle 3xx. Am I wrong?

**Comment by ronag** [comment]
Ah, sorry. My mistake. I’ll take another luck.

**Comment by ronag** [comment]
@ShogunPanda  can you pull in the changes from https://github.com/nodejs/undici/tree/705?

**Comment by ronag** [comment]
I'm a little unsure how `CONNECT` and redirects should behave.

**Comment by ShogunPanda** [comment]
> @ShogunPanda can you pull in the changes from [51bde24](https://github.com/nodejs/undici/commit/51bde2490c054bb9f3b3041b1d4896aa69e62944)?

Sure, will do later tonight.

**Comment by ShogunPanda** [comment]
> I'm a little unsure how `CONNECT` and redirects should behave.

I'm not sure as well. I will read the RFC later and give you an update here.

**Comment by ShogunPanda** [comment]
@ronag I've pulled your commit as requested.

I've also checked the RFC (https://tools.ietf.org/html/rfc7231#section-4.3.6).

It says that unless the server responds with a 2xx, HTTP remains in charge and thus this implies that the server might send a 3xx and we should handle as usual.
At least that's my understanding. :)

**Comment by ronag** [comment]
Landed in https://github.com/nodejs/undici/commit/aeddb6e207ecb5bce8125f0fcc820879cd029933

**Pull request closed without merging**
