### PR TITLE
fix: lazy load llhttp

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/988

### CODE REVIEW

**Comment by mcollina** [comment]
why this fixes #988?

**Comment by ronag** [comment]
Because it doesn't load the binaries when they are not needed. Seems to be a memory limited environment.

**Comment by mcollina** [comment]
It would load them eventually. Maybe they can try this branch before we land it?

**Comment by ronag** [comment]
> It would load them eventually. 

From what I understood from the issue they don't.

**Comment by ronag** [comment]
https://github.com/prisma/prisma/pull/8823

> Because we import both LibraryEngine and BinaryEngine files and undici tries to load the wasm even if not instantiated / needed

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by janpio** [comment]
We did test this branch and it indeed made our tests pass: https://github.com/nodejs/undici/issues/988#issuecomment-902189995

**Pull request merged**
