### PR TITLE
fix(fetch): raise AbortSignal max event listeners

### PR DESCRIPTION
**Pull request by KhafraDev**
Fixes https://github.com/nodejs/node/issues/46525
Refs https://github.com/nodejs/undici/issues/939#issuecomment-1419471112

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
Lgtm

**Comment by ricardocosta** [comment]
@KhafraDev According to https://github.com/remix-run/react-router/issues/10118, this PR introduces errors when using React Router because `getEventListeners` doesn't support signals of type `AbortSignal `, whilst `signal` can be of that type.

Is there any issue/plan to fix this?

**Comment by KhafraDev** [comment]
getEventListeners does work on a nodejs AbortSignal, since it extends EventTarget. If you have a minimal repro that would be helpful.

**Comment by joshkel** [comment]
@KhafraDev, thank you for looking into this. However, I'm still having problems; depending on how quickly my loop runs, Node.js might add >200 event listeners, so I still get these warnings spammed to the console. I tried raising the warning limit  myself (`setMaxListeners(Infinity, this.controller.signal)`); however, this PR overrides any warning limit that was already set.

For a repro for https://github.com/remix-run/react-router/issues/10118, see https://github.com/joshkel/vitest-undici-abort-bug. The problem arises because testing frameworks such as Vitest may cause jsdom's AbortController to be used with undici's fetch.

**Comment by KhafraDev** [comment]
So it does seem like an issue in vitest - overriding some globals is bound to cause issues (see jest...). Although we should offer support for 3rd party AbortControllers, so this is a bug. We also shouldn't be changing the max listeners if the amount was changed, but there's no way of checking so there isn't much to do with that.

**Comment by KhafraDev** [comment]
this was already fixed in undici v5.21.0, node v19.6.0 is using undici v5.19.1.

**Comment by KhafraDev** [comment]
node v19.8+ have the fix

**Comment by sangaman** [comment]
> node v19.8+ has the fix

I'm still seeing this `MaxListenersExceededWarning` with `AbortSignal` on v19.8.1, it appears to be triggered by calling the native `fetch` a handful of times in a test suite.

**Comment by Himself65** [comment]
is there any hotpatch for nodejs 18?

**Comment by ba55ie** [comment]
> is there any hotpatch for nodejs 18?

You can patch `globalThis.fetch` with the latest version from `undici`:

```js
import { fetch } from 'undici';

globalThis.fetch = fetch;
```  

That's how I fixed our tests in node `v18.15.0`:

```js
import { fetch } from 'undici';
import { beforeAll, afterAll, test } from 'your-test-lib';

let originalFetch;

beforeAll(() => {
  originalFetch = globalThis.fetch;
  globalThis.fetch = fetch;
});

afterAll(() => {
  globalThis.fetch = originalFetch;
});

// Run your tests using fetch.
```

**Comment by IanVS** [comment]
Looks like this is now included in node 18.16.0 as well. 👍

**Comment by thw0rted** [comment]
I'm still seeing this with Jest tests on Node 18.16.1:

> (node:10904) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit

Is this PR supposed to address the warning automatically, or am I meant to be manually increasing `setMaxListeners`?

**Comment by Maxlitv** [comment]
> 

I love you.

**Comment by Maxlitv** [comment]
> Looks like this is now included in node 18.16.0 as well. 👍

I love you.

**Pull request merged**
