### PR TITLE
feat: implement missing Request spec

### PR DESCRIPTION
**Pull request by tsctx**

### CODE REVIEW

**Review by KhafraDev — CHANGES_REQUESTED** [review]
this isn't implemented because we don't implement request priority, as the note stated... adding it as an option is not implementing it

**Comment by mcollina** [comment]
Sooo, what's about Request priority? How should it be implemented?

**Comment by KhafraDev** [comment]
https://github.com/nodejs/undici/issues/1748

**Comment by tsctx** [comment]
Okey. I understand.

**Pull request closed without merging**
