### PR TITLE
use worker

### PR DESCRIPTION
**Pull request by ronag**
Just some testing... seems slower unfortunately...

```js
Branch worker set up to track remote branch worker from origin.
Switched to a new branch 'worker'
root@ce8fa663fa44:/undici# node benchmarks/index.js 
http - no agent  x 661 ops/sec ±1.21% (78 runs sampled)
http - keepalive x 691 ops/sec ±1.57% (71 runs sampled)
http - keepalive - multiple sockets x 4,978 ops/sec ±1.38% (78 runs sampled)
undici - pipeline x 5,180 ops/sec ±2.34% (79 runs sampled)
undici - request x 5,424 ops/sec ±1.17% (85 runs sampled)
undici - pool - request - multiple sockets x 3,492 ops/sec ±71.11% (82 runs sampled)
undici - stream x 5,841 ops/sec ±1.01% (82 runs sampled)
undici - dispatch x 5,933 ops/sec ±0.82% (82 runs sampled)
undici - noop x 6,096 ops/sec ±0.84% (82 runs sampled)
root@ce8fa663fa44:/undici# git checkout parser-execute
Branch parser-execute set up to track remote branch parser-execute from origin.
Switched to a new branch 'parser-execute'
root@ce8fa663fa44:/undici# node benchmarks/index.js 
http - no agent  x 654 ops/sec ±1.42% (78 runs sampled)
http - keepalive x 675 ops/sec ±1.24% (80 runs sampled)
http - keepalive - multiple sockets x 4,944 ops/sec ±2.03% (78 runs sampled)
undici - pipeline x 5,970 ops/sec ±1.66% (81 runs sampled)
undici - request x 6,243 ops/sec ±1.62% (78 runs sampled)
undici - pool - request - multiple sockets x 6,292 ops/sec ±0.98% (81 runs sampled)
undici - stream x 6,506 ops/sec ±1.20% (79 runs sampled)
undici - dispatch x 6,645 ops/sec ±1.15% (81 runs sampled)
undici - noop x 6,825 ops/sec ±1.07% (80 runs sampled)
```

### CODE REVIEW

**Comment by ronag** [comment]
@mcollina any ideas on how to optimize? I'm a  little surprised by the result but I guess parsing is not heavy enough relative to the overhead.

**Comment by mcollina** [comment]
Totally expected, moving data back and forth from a worker is expensive.

**Comment by ronag** [comment]
Was a fun experiment.

**Comment by mcollina** [comment]
Indeed, pretty amazing this was even possible, numbers were better than I expected.

**Comment by ronag** [comment]
Managed to optimize a little but still slower.

Worker
```
http - no agent  x 606 ops/sec ±10.82% (79 runs sampled)
http - keepalive x 693 ops/sec ±1.54% (81 runs sampled)
http - keepalive - multiple sockets x 5,166 ops/sec ±1.38% (81 runs sampled)
undici - pipeline x 5,487 ops/sec ±1.77% (82 runs sampled)
undici - request x 5,699 ops/sec ±1.30% (81 runs sampled)
undici - pool - request - multiple sockets x 5,710 ops/sec ±1.18% (83 runs sampled)
undici - stream x 5,904 ops/sec ±1.30% (83 runs sampled)
undici - dispatch x 6,094 ops/sec ±0.98% (83 runs sampled)
undici - noop x 6,246 ops/sec ±0.79% (82 runs sampled)
```

No Worker:
```
http - no agent  x 654 ops/sec ±1.42% (78 runs sampled)
http - keepalive x 675 ops/sec ±1.24% (80 runs sampled)
http - keepalive - multiple sockets x 4,944 ops/sec ±2.03% (78 runs sampled)
undici - pipeline x 5,970 ops/sec ±1.66% (81 runs sampled)
undici - request x 6,243 ops/sec ±1.62% (78 runs sampled)
undici - pool - request - multiple sockets x 6,292 ops/sec ±0.98% (81 runs sampled)
undici - stream x 6,506 ops/sec ±1.20% (79 runs sampled)
undici - dispatch x 6,645 ops/sec ±1.15% (81 runs sampled)
undici - noop x 6,825 ops/sec ±1.07% (80 runs sampled)
```

**Pull request closed without merging**
