### PR TITLE
feat: change headersTimeout to 300s

### PR DESCRIPTION
**Pull request by kyrylkov**

### CODE REVIEW

**Review by ronag — COMMENTED** [review]
Isn't it enough to change the headers timeout?

**Comment by kyrylkov** [comment]
I guess. Should I modify?

**Comment by kyrylkov** [comment]
Done

**Review by ronag — APPROVED** [review]

**Comment by mcollina** [comment]
why is this just a docs change?

**Comment by kyrylkov** [comment]
Sorry :(  Fixed now.

**Review by ronag — APPROVED** [review]

**Comment by mcollina** [comment]
CI is failing

**Comment by kyrylkov** [comment]
It says "failed 1 of 86 tests", but what exactly I cannot find.  Can you?

**Comment by KhafraDev** [comment]
test/request-timeout.js

**Comment by kyrylkov** [comment]
I am sorry but I don't see where it's failing and I don't see why.  

Let me know if you want to keep it open or I should close it.

**Comment by kyrylkov** [comment]
@KhafraDev I don't see `request-timeout.js` failing

image

I do see `fetch/abort.js` failing and I cannot figure out why

image

**Comment by KhafraDev** [comment]
<details>

```
    # Subtest: stream timeout
        1..1
        not ok 1 - Should not be called
          ---
          at:
            line: 626
            column: 9
            file: test/request-timeout.js
          stack: |
            test/request-timeout.js:626:9
            StreamHandler.onHeaders (lib/api/api-stream.js:1:20335)
            Request.onHeaders (lib/core/request.js:13:10337)
            Parser.onHeadersComplete (lib/client.js:28:96)
            wasm_on_headers_complete (lib/client.js:17:1842)
            wasm-function[11]:0x494
            wasm-function[51]:0x1003
            wasm-function[68]:0x7046
            wasm-function[67]:0x155d
            wasm-function[21]:0x552
            Parser.execute (lib/client.js:25:184)
            Parser.readMore (lib/client.js:21:391)
            Socket.onSocketReadable (lib/client.js:37:1132)
          source: "    }, (result) => {\r
          
            \      t.fail('Should not be called')\r
          
            --------^
          
            \    }, (err) => {\r
          
            \      t.type(err, errors.HeadersTimeoutError)\n"
          ...
        
        # failed 1 test
    not ok 18 - stream timeout # time=-603555.004ms
    
    # Subtest: stream custom timeout
        1..1
        ok 1 - type is HeadersTimeoutError
    ok 19 - stream custom timeout # time=-603577.07ms
    
    # Subtest: pipeline timeout
        1..1
        not ok 1 - Should not be called
          ---
          at:
            line: 707
            column: 11
            file: test/request-timeout.js
          stack: |
            test/request-timeout.js:707:11
            PipelineHandler.onHeaders (lib/api/api-pipeline.js:2:1446)
            Request.onHeaders (lib/core/request.js:13:10337)
            Parser.onHeadersComplete (lib/client.js:28:96)
            wasm_on_headers_complete (lib/client.js:17:1842)
            wasm-function[11]:0x494
            wasm-function[51]:0x1003
            wasm-function[68]:0x7046
            wasm-function[67]:0x155d
            wasm-function[21]:0x552
            Parser.execute (lib/client.js:25:184)
            Parser.readMore (lib/client.js:21:391)
            Socket.onSocketReadable (lib/client.js:37:1132)
          source: "      }, (result) => {\r
          
            \        t.fail('Should not be called')\r
          
            ----------^
          
            \      }, (e) => {\r
          
            \        t.fail('Should not be called')\n"
          ...
        
        # failed 1 test
    not ok 20 - pipeline timeout # time=-603581.501ms
    
    # Subtest: pipeline timeout
        1..1
        ok 1 - type is HeadersTimeoutError
    ok 21 - pipeline timeout # time=-603603.37ms
    
    # Subtest: client.close should not deadlock
        1..2
        ok 1 - type is HeadersTimeoutError
        ok 2 - should not error
    ok 22 - client.close should not deadlock # time=-634512.15ms
    
    not ok 23 - The client is destroyed
      ---
      at:
        line: 2
        column: 1519
        file: lib/dispatcher-base.js
        function: Client.destroy
      stack: |
        Client.destroy (lib/dispatcher-base.js:2:1519)
        lib/dispatcher-base.js:2:611
        new Promise (<anonymous>)
        Client.destroy (lib/dispatcher-base.js:2:529)
      type: ClientDestroyedError
      code: UND_ERR_DESTROYED
      tapCaught: uncaughtException
      test: TAP
      source: "'use strict'\r
      
        \r
      
        const Dispatcher = require('./dispatcher')\r
      
        const {\n"
      ...
    
    1..23
    # failed 3 of 23 tests
    # skip: 1
    # time=1238.143ms
not ok 69 - test/request-timeout.js # time=1238.143ms
  ---
  env: {}
  file: test/request-timeout.js
  timeout: 60000
  command: C:\hostedtoolcache\windows\node\12.22.12\x64\node.exe
  args:
    - --expose-gc
    - --experimental-wasm-simd
    - test/request-timeout.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\a\undici\undici
  exitCode: 1
  ...
````
</details>

**Comment by kyrylkov** [comment]
@KhafraDev Pushed updated `request-timeout.js`, but `fetch/abort2.js` still failes

**Comment by KhafraDev** [comment]
that test fails locally, works in the ci

**Comment by kyrylkov** [comment]
@KhafraDev Well, that's confusing, but OK.  How can CI tests be restarted after my latest commit?

**Comment by KhafraDev** [comment]
they should re-run automatically, I'm not sure why they weren't queued

**Comment by kyrylkov** [comment]
@KhafraDev can you manually start CI?

**Comment by mcollina** [comment]
you can force push or add a tiny commit to trigger them again

**Comment by kyrylkov** [comment]
@mcollina I just did and nothing happened again https://github.com/nodejs/undici/pull/1924/commits/ee9c9cdd4e77a979329648498fdc94e486691a1b

**Comment by mcollina** [comment]
I don’t know what’s the problem, it might be a glitch in GitHub actions. Try opening a fresh PR.

**Pull request closed without merging**
