### PR TITLE
test: improve coverage on agent and pool

### PR DESCRIPTION
**Pull request by jarrodconnolly**
Related to https://github.com/nodejs/undici/issues/438
Started adding some tests to improve coverage. When writing the test for `dispatcher.running`

I realized the iteration in agent `connected`, `size`, `pending`, and `running` was not taking the WeakRef into account.

Wanted to get this change in if it looks good and get back to more tests in another PR.

### CODE REVIEW

**Review by ronag — APPROVED** [review]
Good catch!

**Review by ronag — CHANGES_REQUESTED** [review]
You need to check for `undefined` after `.deref()`.

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
can you please resolve the conflicts?

**Comment by ronag** [comment]
Please fix conflict

**Review by Ethan-Arrowood — APPROVED** [review]

**Review by dnlup — APPROVED** [review]
lgtm once conflicts are fixed

**Comment by jarrodconnolly** [comment]
Resolved and fixed the new tap 15 warnings in the tests I added.

**Pull request merged**
