### PR TITLE
chore: update `pkgjs/action` from 0.1.7 to 0.1.9

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## This relates to...

Closes https://github.com/nodejs/undici/pull/2486

## Rationale

Tests of https://github.com/nodejs/undici/pull/2486 are failed for Node.js v21 matrix. The difference seems to have occurred because the row of console.table is now aligned to the left ( https://github.com/nodejs/node/pull/50135 ).

So this PR uses left aligned tables for testing when running on node v21 and above.

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [S] Benchmarked (**optional**)
- [S] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by dominykas** [comment]
Please consider unpinning the version (see https://github.com/nodejs/undici/pull/2434 for reasoning).

**Comment by sosukesuzuki** [comment]
> Please consider unpinning the version of this action (see https://github.com/nodejs/undici/pull/2434 for reasoning).

@dominykas I'm new to this project and so would like to know what maintainers think.

**Comment by sosukesuzuki** [comment]
@mcollina @ronag What do you think? In general, I think that keeping the version fixed makes CI more stable and safer.

**Comment by sosukesuzuki** [comment]
Suppressed by https://github.com/nodejs/undici/pull/2434

**Pull request closed without merging**
