### PR TITLE
fix: copy buffers

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/710

### CODE REVIEW

**Comment by ronag** [comment]
@indutny

**Comment by ronag** [comment]
Not sure if there is a faster way to copy which doesn't not involved creating a temporary `Buffer`.

**Comment by indutny** [comment]
I think this should be about as fast as it can be, but you could experiment by creating a buffer from buffer something like wrapping your previous `Buffer.from()` calls with another `Buffer.from()`. The benefit of latter is that you don't do unsafe allocations.

**Comment by ronag** [comment]
@indutny: Another question. Would it be possible for `wasm_on_header_` to instead point into the buffer passed to `execute`?  That way no copy would be required.

**Comment by indutny** [comment]
@ronag that buffer is relative to the input of the `execute` already. I think the problem is that you copy it into wasm memory and so you get back a slice of the very same memory you copied it to. Not sure if there is a way to pass data to wasm without copying. Perhaps shared buffers?

**Review by mcollina — APPROVED** [review]
I have a feeling that this unwinds any gain we got by using buffers for Headers, would not be better to revert?

Anyway LGTM

**Comment by ronag** [comment]
> I have a feeling that this unwinds any gain we got by using buffers for Headers, would not be better to revert?
> 
> Anyway LGTM

I still haven’t given up. I think I can sort this as zero copy still.

**Pull request merged**
