### PR TITLE
port Header class changes from core PR#38986

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
This PR ports some of the changes I've made in https://github.com/nodejs/node/pull/38986 

Includes an argument length check as well that isn't in my core PR yet

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm but it makes me uncomfortable in keep landing changes without tests.

**Comment by ronag** [comment]
@mcollina It's only fetch related changes that we land without tests. I think this is good in order to keep velocity up and it adds a natural place for new contributors to help us. If you are still uncomfortable then I guess we can slow down a bit and focus on tests. I was hoping to try and implement functionality and then focus on tests before release.

**Comment by ronag** [comment]
@Ethan-Arrowood would be great if we could port over the tests from undici-fetch.

**Comment by mcollina** [comment]
> @mcollina It's only fetch related changes that we land without tests. I think this is good in order to keep velocity up and it adds a natural place for new contributors to help us. If you are still uncomfortable then I guess we can slow down a bit and focus on tests. I was hoping to try and implement functionality and then focus on tests before release.

That'd be ok if it's a feature branch and not main. Anyway, let's see what the timeline is... we can always move this into a different branch.

**Comment by ronag** [comment]
> That'd be ok if it's a feature branch and not main

Yes you are totally right. Apologies.

**Pull request merged**
