### PR TITLE
fix: workflow commit user

### PR DESCRIPTION
**Pull request by tsctx**
## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Why?

**Comment by Uzlopak** [comment]
Then you see the right icon and it is well known to be a github action

**Pull request merged**
