### PR TITLE
Autobahn suite

### LINKED ISSUE #3249: running autobahn test suite
We cannot move WebSocket out from experimental until we run the autobahn test suite.

https://github.com/crossbario/autobahn-testsuite

### PR DESCRIPTION
**Pull request by KhafraDev**
Closes #3249

### CODE REVIEW

**Comment by KhafraDev** [comment]
before: 
image

after:
image

**Comment by Uzlopak** [comment]
Nice. Let me have a look at it. A little bit annoying, that you cant see the progress.

**Review by Kris35hoog — COMMENTED** [review]
Ok

**Comment by Uzlopak** [comment]
@KhafraDev 

I run it now for 20 min, and nothing showed up. Or does it take much longer? Did you forget the server?

**Comment by Uzlopak** [comment]
Ah. I get it now. Run the run.sh and then run client.js with node

**Review by Uzlopak — APPROVED** [review]
The PR-comment action can only work, after we merged this PR into main.

**Review by tsctx — APPROVED** [review]

**Pull request merged**
