### PR TITLE
separate whatwg websocket logic from rfc 6455

### PR DESCRIPTION
**Pull request by KhafraDev**
refs: https://github.com/nodejs/undici/pull/3394#discussion_r1667601624

cc @tsctx

### CODE REVIEW

**Comment by KhafraDev** [comment]
There is still a lot of clunkiness to fix.

**Review by tsctx — APPROVED** [review]

**Comment by tsctx** [comment]
This PR is very good, but it might be better to use an internal class and manage all conditions and hooks there.

**Comment by KhafraDev** [comment]
I agree, we can continue working on it later.

**Review by tsctx — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
rlgtm

**Review by metcoder95 — APPROVED** [review]

**Pull request merged**
