### PR TITLE
test: improve gc detection

### PR DESCRIPTION
**Pull request by Uzlopak**
Now it will throw a helpful error, when gc is not exposed

image

### CODE REVIEW

**Comment by KhafraDev** [comment]
not running the tests is worse than throwing an error imo

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — CHANGES_REQUESTED** [review]
Actually, the test should fail

**Comment by Uzlopak** [comment]
@mcollina 
@KhafraDev 
PTAL

**Review by KhafraDev — APPROVED** [review]

**Pull request merged**
