### PR TITLE
missing commits

### PR DESCRIPTION
**Pull request by ronag**
Refs: https://github.com/nodejs/undici/issues/3033

### CODE REVIEW

**Comment by ronag** [comment]
@metcoder95 I can't apply https://github.com/nodejs/undici/commit/fa5bcb4597cf662af28e6f9a30f6afbdc5c5381a

**Comment by metcoder95** [comment]
> @metcoder95 I can't apply [fa5bcb4](https://github.com/nodejs/undici/commit/fa5bcb4597cf662af28e6f9a30f6afbdc5c5381a)

Does it have conflicts or how so?

**Comment by metcoder95** [comment]
I'll open a PR for it

**Comment by ronag** [comment]
I think I managed. Though I lost your author ship.

**Comment by metcoder95** [comment]
Perfect, that's fine tho 👍

**Review by mcollina — APPROVED** [review]
lgtm

This needs to be landed as "rebase and merge" otherwise we lose commit history

**Pull request merged**
