### PR TITLE
fix: correct firing order of abort events

### LINKED ISSUE #2227: abortcontroller & request.clone issue with fetch
```js
  import { Request } from 'undici'
  import { ok, strictEqual } from 'node:assert'

  const controller = new AbortController();
  const signal = controller.signal;

  const request = new Request('http://a', { signal });
  const clonedRequest = request.clone();

  const log = [];

  request.signal.addEventListener('abort', () => log.push('original-aborted'));
  clonedRequest.signal.addEventListener('abort', () => log.push('clone-aborted'));

  controller.abort();

  strictEqual(log, ['original-aborted', 'clone-aborted'], "Abort events fired in correct order");
  ok(request.signal.aborted, 'Signal aborted');
  ok(clonedRequest.signal.aborted, 'Signal aborted');
```

cc @atlowChemi since you recently made a PR regarding abortcontroller, hopefully you can help. I don't know enough about EventTarget and order of events to fix this

### PR DESCRIPTION
**Pull request by tsctx**
Fixes #2227

I’ｍ happy to be able to add undici to a test that has only passed Chrome and Deno yet.

https://wpt.fyi/results/fetch/api/abort/general.any.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=deno&product=node.js&aligned=

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
if we had a unit test, which was based on the original reported bug, it would be easier to approve :P. I know we have the wpt test, but for an approval I would need to check out this PR and check what the wpt test does...

**Review by Uzlopak — APPROVED** [review]
RSLGTM

**Review by KhafraDev — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
