### PR TITLE
fix: don't add listeners to the same signal more than once

### PR DESCRIPTION
**Pull request by tsctx**

### CODE REVIEW

**Comment by ronag** [comment]
What is this solving?

**Comment by tsctx** [comment]
#3131

**Comment by Uzlopak** [comment]
But isnt it a bug in the product too, that it tries to add again and again the same listeners? Not saying we should not solve it here. But now it hints to a bug, but after we merge this you dont get a hint that something is wrong.

**Comment by ronag** [comment]
I don't think we should merge this. It doesn't solve an actual bug. It just bypasses the warning.

**Review by ronag — CHANGES_REQUESTED** [review]
Se above

**Comment by tsctx** [comment]
> But isnt it a bug in the elasticsearch client too, that it tries to add again and again the same listeners? 

elasticsearch client is not the cause of the problem, it is undici-specific. In fact, it does not leak.

> Not saying we should not solve it here. But now it hints to a bug, but after we merge this you dont get a hint that something is wrong.

When a signal was given and a large number of requests were sent at once (easy to see in the test), listeners were added more than the limit and a warning was generated.

**Comment by metcoder95** [comment]
> > Not saying we should not solve it here. But now it hints to a bug, but after we merge this you dont get a hint that something is wrong.
> 
> When a signal was given and a large number of requests were sent at once (easy to see in the test), listeners were added more than the limit and a warning was generated.

I am not sure if we should consider that an `undici` problem. This issue is potentially everywhere and it seems we are trying to protect the users from themselves when they should be aware of how they handle their signals and others.
No strong opinion on this, but I'd advise considering if worth the complexity given this is more a problem of how is `AbortSignal` used by the user rather than by `undici`.

**Comment by tsctx** [comment]
Oh, you are right.

**Pull request closed without merging**
