### PR TITLE
Fix node detection omfg

### PR DESCRIPTION
**Pull request by KhafraDev**
I confirmed tests pass and it works in node.

### CODE REVIEW

**Review by Ethan-Arrowood — APPROVED** [review]
I like this much more. ship it

**Comment by KhafraDev** [comment]
test seems to fail on windows for some reason

**Comment by merceyz** [comment]
Instead of a plugin couldn't you use the [`--define`](https://esbuild.github.io/api/#define) flag for this?

**Comment by Ethan-Arrowood** [comment]
Didn't even know that was an option! I think that should work nicely.

**Comment by KhafraDev** [comment]
We only bundle undici for node core, I don't see the difference between the two unless we started bundling undici for npm.

**Comment by Ethan-Arrowood** [comment]
It might just be a simpler solution. I'm fine with either way

**Comment by KhafraDev** [comment]
Let's merge this as is so we can land the undici update and then we can look into other solutions. I'm not home anymore so would you mind merging and releasing an update? Thanks

**Comment by Ethan-Arrowood** [comment]
Done here: https://github.com/nodejs/undici/releases/tag/v5.26.1

**Pull request merged**
