### PR TITLE
perf: use @fastify/busboy

### PR DESCRIPTION
**Pull request by gurgunday**
## Rationale

It is much faster

```shell
| Node    | Option         | Msecs/op       | Ops/sec  | V8                    |
| ------- | -------------- | -------------- | -------- | --------------------- |
| 20.5.0  | fastify-busboy | 0.110761 msecs | 9028.472 | V8 11.3.244.8-node.10 |
| 20.5.0  | busboy         | 0.210623 msecs | 4747.830 | V8 11.3.244.8-node.10 |
| 16.13.0 | fastify-busboy | 0.270984 msecs | 3690.248 | V8 9.4.146.19-node.13 |
| 16.13.0 | busboy         | 0.340114 msecs | 2940.190 | V8 9.4.146.19-node.13 |
| 12.22.7 | busboy         | 1.945927 msecs | 513.894  | V8 7.8.279.23-node.56 |

**Specs**: M1 (2.4 GHz)
```

## Status

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [x] Tested
- [x] Benchmarked (**optional**)
- [x] Documented
- [x] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by ronag — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by KhafraDev** [comment]
why did the test need to be changed?

**Comment by gurgunday** [comment]
> why did the test need to be changed?

@KhafraDev in that specific test (where the boundary is malformed), instead of throwing,Fastify Busboy accepts the header and returns an empty object

I checked the standard to see what the proper way of handling is... and I'm not sure that it's clearly specified - Fastify Busboy only throws when the boundary property is entirely missing

**Comment by KhafraDev** [comment]
thanks, a test needs to be added that makes sure that an invalid boundary string causes .formData() to throw an error.

**Comment by gurgunday** [comment]
So just to make sure: you want the original test to pass, meaning a malformed boundary should still throw, right?

Or would you like me to put the boundary back and verify that it returns an empty object (test the new behavior)?

**Comment by KhafraDev** [comment]
the former, a malformed boundary should throw

**Comment by gurgunday** [comment]
@KhafraDev PTAL again

Benchmark on M1 Macbook:
```shell
{ cpu: { brand: 'M1', speed: '2.4 GHz' } }
| Node    | Option         | Msecs/op       | Ops/sec  | V8                    |
| ------- | -------------- | -------------- | -------- | --------------------- |
| 20.6.0  | fastify-busboy | 0.110915 msecs | 9015.906 | V8 11.3.244.8-node.14 |
| 20.6.0  | busboy         | 0.207797 msecs | 4812.393 | V8 11.3.244.8-node.14 |
```
Source: https://github.com/fastify/busboy/tree/master/benchmarks

**Comment by KhafraDev** [comment]
`test/client-request.js` seems to be failing everywhere

**Comment by gurgunday** [comment]
Wow, I missed that...

**Comment by gurgunday** [comment]
All tests are passing on my machine

**Comment by KhafraDev** [comment]
thank you for putting up with my concerns

**Comment by gurgunday** [comment]
It's my pleasure!

You were just pointing out important inconsistencies 🚀

**Pull request merged**
