### PR TITLE
fix: tick timer instead of using Date.now

### PR DESCRIPTION
**Pull request by ronag**
Partially fixes some of the timeout issues we have been facing. Again needs work with tests.

Refs: https://github.com/nodejs/undici/issues/3493

## Status

- [ ] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by mcollina** [comment]
I'm generically ok with the change, but I would be happier with tests. Maybe one from @Uzlopak's PR?

**Comment by ronag** [comment]
I suspect that or includes this change somewhere

**Comment by Uzlopak** [comment]
This PR is replacing the Date.now() call with saying that every time setTimeout is triggered that 499 ms are passed. This means, that if the event loop blocks for e.g. 900ms, we still "think" that just 499ms passed.  So the fasttimer will be artificially delayed.

**Comment by Uzlopak** [comment]
We could change it in my PR to just increment the fastNow value instead of calling performance.now. But somehow it feels wrong.

**Comment by ronag** [comment]
The whole point is that we don't want to include event loop delay

**Comment by Uzlopak** [comment]
adapted
https://github.com/nodejs/undici/pull/3495/commits/ad339a2feddf08267e287799332cd5ed48ba799a

**Pull request closed without merging**
