### PR TITLE
feat: add http2

### PR DESCRIPTION
**Pull request by Nytelife26**
## This relates to...

- #547

## Rationale

HTTP/2 support is one of the few things currently missing from Undici
that sets it behind native Node `http`.

## Changes

This pull request is a work in progress. There are no changes just
yet. The plan, however, as discussed in the original issue, is to
implement HTTP/2 support around a `Dispatcher` instance for `Pool`,
`Client` and `Agent`.

Implementation can work in one of the following ways (see RFC7540 and
RFC8740):
1. **Prior knowledge**
  - Servers using HTTP/2 can advertise the capability via methods like ALT-SVC
  - Under RFC7540 Section 3.5, the HTTP/2 connection preface must be sent
  - All future frames may immediately use the HTTP/2
2. **HTTP/1.1 Initialization** (servers where HTTP/2 support status is unknown)
  - Without prior knowledge, the client should start an HTTP/1.1 connection
  using the Upgrade header (`h2c` for http URI schema, `h2` for TLS) and
  HTTP2-Settings header
  - If the response is a HTTP 101 Switching Protocols request, the request
  will be accompanied by a response to prior requests and the connection can
  upgrade to HTTP/2. If the response is normal, exempli gratia, a HTTP 200 OK,
  the client must not switch to  HTTP/2.

As for HTTPS, TLS negotiation must occur prior to any upgrade to HTTP/2.

### Features

HTTP/2 variants of `Pool`, `Client` and `Agent`. Alternatively, an option in the
aforementioned classes that causes them to attempt a HTTP/2 upgrade.

### Bug Fixes

N/A.

### Breaking Changes and Deprecations

N/A.

## Status

KEY: S = Skipped, x = complete

- [x] I have read and agreed to the [Developer's Certificate of Origin][cert]
- [ ] Tested
- [ ] Benchmarked (**optional**)
- [ ] Documented
- [ ] Review ready
- [ ] In review
- [ ] Merge ready

[cert]: https://github.com/nodejs/undici/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by Nytelife26** [comment]
@mcollina as noted in the "Features" section of this pull request, we have two options.

> "HTTP/2 variants of Pool, Client and Agent. Alternatively, an option in the
aforementioned classes that causes them to attempt a HTTP/2 upgrade."

We have only discussed the prior, so I'd like to take this opportunity to ask what the desired approach is before I begin.

**Comment by ronag** [comment]
I don't think you need to develop a new `Agent` or `Pool`. What we need is either modify existing `Client` to support both or create a new `Http2Client`, rename `Client` to `HttpClient` and then create another `Client` that somehow switches between the two as needed.

**Comment by mcollina** [comment]
I would just focus on creating a `Http2Client` right now.

The hardest part is figuring out is the upgrade to HTTP/2

**Comment by szmarczak** [comment]
@mcollina This is pretty easy. All we need to do is just create a TLS connection and check the ALPN protocol. Something like:

```
if (socket.alpnProtocol === 'h2') {
    const session = http2.connect(origin, {
        createConnection: () => socket
    });
    ...
}

const client = new HttpClient(socket);
...
```

**Comment by Nytelife26** [comment]
> All we need to do is just create a TLS connection and check the ALPN protocol.

That depends - the protocol is different depending on whether the desired connection is HTTPS or HTTP. As I mentioned, if TLS is present, you must use ALPN first. If not, you have to follow the standard HTTP Upgrade procedure.

**Comment by ronag** [comment]
I think http2 should always be https? I don’t think we need to support the non TLS case for http2.

**Comment by Nytelife26** [comment]
> I think http2 should always be https? I don’t think we need to support the non TLS case for http2.

That doesn't sit right with me. We shouldn't just ignore usages that are part of the specification itself for our own convenience, especially when it'll likely result in someone filing an issue later on.

**Comment by mcollina** [comment]
> I think http2 should always be https? I don’t think we need to support the non TLS case for http2.

It's needed and used within microservices networks.

**Comment by szmarczak** [comment]
> We shouldn't just ignore usages that are part of the specification itself for our own convenience

[`undici` already does](https://github.com/nodejs/undici#specification-compliance).

> I think http2 should always be https? I don’t think we need to support the non TLS case for http2.

I thought the same - browsers don't. 

> It's needed and used within microservices networks.

I believe there are better solutions in these cases. Anyway they can just use the native `http2.connect` instead.

**Comment by Nytelife26** [comment]
> It's needed and used within microservices networks.

Thank you.



> [`undici` already does](https://github.com/nodejs/undici#specification-compliance).

That's not quite the same as dropping an entire protocol. Although, I do trust and hope there are technical reasons for not following those parts too.

> I thought the same - browsers don't [support h2c].

Not yet. Most of the point of HTTP/2 was for browsers so It most likely will.

> I believe there are better solutions in these cases. Anyway they can just use the native `http2.connect` instead.

You could also argue that you could use the native `http` instead of undici altogether. But the point of undici is that it is faster. So yes, they *can* use an inferior solution, but I see no reason to not do our best just because other solutions already exist.

**Comment by szmarczak** [comment]
> Most of the point of HTTP/2 was for browsers so It most likely will.

I don't think `h2c` is coming anytime soon. Even [CloudFlare doesn't support it](https://community.cloudflare.com/t/http-h2c-upgrade-requests-result-in-connection-reset-by-peer/214761).

> you could use the native http instead of undici altogether

That's not quite the same as `undici` is a complete rewrite, it doesn't use the `http` module internally. The point is that for now you have to use `http2.connect(...)` anyway. The API is very friendly so people should use it directly whenever the can.

I'd prefer if `undici` targeted HTTP/2 with TLS first, but if anybody wants to go after `h2c` as well - I don't mind.

**Comment by mcollina** [comment]
FYI: Google Cloud Run supports h2c https://cloud.google.com/run/docs/configuring/http2.

My take is that h2c support might be really handy.

**Comment by kanongil** [comment]
h2c is super useful for debugging tricky protocol issues using Wireshark, etc.

**Comment by Nytelife26** [comment]
## Summary

> "What we need is either modify existing `Client` to support both or create a new `Http2Client`, rename `Client` to `HttpClient` and then create another `Client` that somehow switches between the two as needed."

**Decision**: To start with, I will be implementing the methods on a new `Http2Client`. It is likely that I will then merge those under an option into `Client`, given that a client with switching may be hard to maintain and create unnecessary overhead, depending on how complex the `Http2Client` will be.

> The hardest part is figuring out is the upgrade to HTTP/2

**Decision**:
- For TLS connections, the TLS side *must* be handled first. Then, we can follow standard procedure.
- The client will either initialize or use the existing HTTP/1.1 connection and send a request with the HTTP `Upgrade` (value of `h2` for HTTPS, `h2c` for HTTP) and `HTTP2-Settings` headers.
  - Implementation on capability advertisement via things like ALT-SVC is currently unclear.
- If the response is a HTTP 101, check for responses to prior requests and begin using HTTP/2. Else, do not switch to HTTP/2.

> I'd prefer if `undici` targeted HTTP/2 with TLS first, but if anybody wants to go after `h2c` as well - I don't mind.

**Decision**: As aforementioned, TLS support is part of the natural protocol of any HTTP/2 upgrade. It is an extension, not a separate method, and therefore both can be achieved simultaneously.

**Comment by Nytelife26** [comment]
Does anyone here know about polyfill support for [`base64url`](https://github.com/nodejs/node/commit/f8ab632d56ea15c78b1dc5db1624109a2bf7b69b) and whether it would be possible to implement it here? The HTTP/2 specification requires that the `HTTP2-Settings` header be encoded in `base64url` (without padding), however, it seems to be a recent feature and I am uncertain of how it would affect compatibility if we were to use it here.

**Comment by panva** [comment]
@mcollina you can take inspiration from https://github.com/panva/jose/blob/main/src/runtime/node/base64url.ts

**Comment by Nytelife26** [comment]
What's the situation regarding `client.upgrade`? It's somewhat vital for this to work, however it doesn't seem to be implemented on `Client` or `Dispatcher`, despite what the documentation says.

image

**Comment by ronag** [comment]
The api methods are assigned to the prototypes in index.js. See, https://github.com/nodejs/undici/blob/main/index.js#L15.

**Comment by Nytelife26** [comment]
Interesting, thank you, that didn't display in GitHub search weirdly. Peculiar approach, but it makes life easier actually since I can avoid a circular dependency between the client and its http2 variant when they merge.

**Comment by Nytelife26** [comment]
Can we safely implement a wider `Client.upgrade` return context? It only provides the headers and socket, but I need the full response body too.

**Comment by Nytelife26** [comment]
> Can we safely implement a wider `Client.upgrade` return context? It only provides the headers and socket, but I need the full response body too.

cc: @ronag @mcollina 

See my above comment when you have the time, please and thank you in advance.

**Comment by ronag** [comment]
> Can we safely implement a wider `Client.upgrade` return context? It only provides the headers and socket, but I need the full response body too.

No idea. As far as I know there is no body after upgrade so I'm not sure what you mean here...

**Comment by Nytelife26** [comment]
> As far as I know there is no body after upgrade

According to the HTTP/2 specification, the server may bundle the
response frames to any previous requests along with its upgrade
acknowledgement. For that reason, I need to be able to access the
response body in order to check for those.

**Comment by Nytelife26** [comment]
Answers, anyone?

**Comment by ronag** [comment]
> Answers, anyone?

I don’t have a better answer. As far as I know there is no body with an upgrade so your question doesn’t make sense to me. Sorry. Maybe I’m missing something...

**Comment by ronag** [comment]
> Right after sending the 101 status code, the server can begin speaking the new protocol, performing any additional protocol-specific handshakes as necessary. Effectively, the connection becomes a two-way pipe as soon as the upgraded response is complete, and the request that initiated the upgrade can be completed over the new protocol.

**Comment by mcollina** [comment]
> Answers, anyone?

I didn't thought it was a question, more of a statement. I'd recommend to try and see if it's possible.

**Comment by Nytelife26** [comment]
I can not continue to work on this, unfortunately. I have pushed my most recent work and hopefully that in combination with this discussion will serve useful to anyone willing to pick up. I apologise and wish you all well, but I no longer have the time, as I have packages to maintain and college is a heavy weight.

**Comment by MetCoder95** [comment]
Hi! I would like to take it over and continue the work, but to be honest, I would need some time to sync completely with both the PR and the HTTP/2 spec, I'll do some lecture over the weekend to start putting hands-on, hope it's ok 🙂

**Comment by Nytelife26** [comment]
> Hi! I would like to take it over and continue the work, but to be honest, I would need some time to sync completely with both the PR and the HTTP/2 spec, I'll do some lecture over the weekend to start putting hands-on, hope it's ok 🙂

Wonderful - I'm sure the team will appreciate your help. I documented most of the important design decisions and wrote my notes here since parsing both RFCs in their entirety is a mammoth task, so I hope they're of use to you. Good luck, and I'll be here for reviews when it's done at least.

**Comment by MetCoder95** [comment]
Sadly I think I don't have write rights to the branch, any suggestion?

**Comment by ronag** [comment]
Open a new PR

**Comment by MetCoder95** [comment]
Closed in favor of #866

**Comment by MetCoder95** [comment]
Just to double-check and give a life signal 😅 
The way to move forward will be using the native `http2` module from `node`?
And if so, any suggestion on how the abstraction/client should look like? :)

**Comment by mcollina** [comment]
> Just to double-check and give a life signal 😅 
> 
> The way to move forward will be using the native `http2` module from `node`?

Yes.

> And if so, any suggestion on how the abstraction/client should look like? :)

I think this was extensively covered in this PR. To be honest, having _something_ that worked would be a good starting point. My suggestion is to start by creating a HTTP2Client.

**Comment by MetCoder95** [comment]
I think @szmarczak is already working on a new PR adding HTTP/2. Happy to take a look at if so, really interested in how does it works 🙂

**Comment by Nytelife26** [comment]
> I think @szmarczak is already working on a new PR adding HTTP/2. Happy
> to take a look at if so, really interested in how does it works 🙂

As far as I've seen, using node core `http2`, despite our former
discussions. Either way, hopefully it'll turn out well.

**Comment by simoneb** [comment]
Is there any work being done on this?

**Comment by Nytelife26** [comment]
> Is there any work being done on this?

Not to my knowledge, feel free to take over.

**Comment by MetCoder95** [comment]
I'll try to revisit it as soon as I have time, but I think @szmarczak has some progress already

**Comment by metcoder95** [comment]
Superseded by #2061

**Pull request closed without merging**
