### PR TITLE
fix: socket back pressure memory leak

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/434

### CODE REVIEW

**Comment by ronag** [comment]
@szmarczak

**Comment by ronag** [comment]
@mcollina I would very much like to make a release out of this as soon as possible.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
go for it!

**Comment by szmarczak** [comment]
Is `socket[kBuffer]` supposed to be `null`?

**Comment by ronag** [comment]
`socket[kBuffer]`?

**Comment by szmarczak** [comment]
https://github.com/nodejs/node/blob/62c44af5c5f2964849bba92ff90c32e867d63f83/lib/net.js#L599-L605

**Comment by ronag** [comment]
Hm, I don't understand how that works at the moment unfortunately.

**Comment by ronag** [comment]
@mcollina Do we know someone that knows these internals well and we could ask for a quick review in regards to `consume` and socket.

**Comment by ronag** [comment]
Seems like whatever `kBuffer` does it's opt-in. https://github.com/nodejs/node/pull/25436

**Comment by szmarczak** [comment]
I think @mcollina was right here: https://github.com/nodejs/node/pull/25436/files#diff-e6ef024c3775d787c38487a6309e491dR602 Overriding Stream API sounds like a mistake.

**Comment by szmarczak** [comment]
Why does it override `.read()` at all? Shouldn't it set `._read()` instead?

**Comment by ronag** [comment]
> Why does it override .read() at all? Shouldn't it set ._read() instead?

What overrides it?

**Comment by ronag** [comment]
> I think @mcollina was right here: nodejs/node#25436 (files) Overriding [public] Stream API sounds like a mistake.

Where is that comment?

**Comment by szmarczak** [comment]
> Where is that comment?

`lib/net.js` after line 603

If you click the `(files)` link it should scroll down to the comment. It is marked as resolved so you need to click `Show conversation`.

<details>
<summary>Screenshot</summary>

image

</details>

> What overrides it?

I'm still talking about Node.js core (lib/net.js file) :sweat_smile: 

image

Shouldn't it be:

```diff
-Socket.prototype.read = function(n) {
+Socket.prototype._read = function(n) {
  if (this[kBuffer] && !this.connecting && this._handle &&
      !this._handle.reading) {
    tryReadStart(this);
  }
- return stream.Duplex.prototype.read.call(this, n);
};
```

**Comment by ronag** [comment]
@szmarczak Yea, that's a bit weird... does it affect us though?

**Pull request merged**
