### PR TITLE
fix(types): make `RequestInit` properties assignable

### LINKED ISSUE #1445: Remove `readonly` from `RequestInit` typings
## Bug Description

It'd be good to remove `readonly` modifier from `RequestInit` typings to match https://github.com/microsoft/TypeScript/blob/95731f03979985609c9fd662f179be5b9cea3470/lib/lib.dom.d.ts#L1470. This would allow for `RequestInit` objects to be conditionally mutated like so https://github.com/ferdikoomen/openapi-typescript-codegen/blob/0f11ea84a9ca9867bb72700f468fa21d8085ce86/src/templates/core/fetch/sendRequest.hbs#L20

I'm happy to raise a PR for this if there are no objections.

## Reproducible By

If you try to mutate a `RequestInit` object, TypeScript will say something like:

> Cannot assign to 'credentials' because it is a read-only property. ts(2540)

## Expected Behavior

No error.

### PR DESCRIPTION
**Pull request by NMinhNguyen**
Fixes #1445

### CODE REVIEW

**Review by KhafraDev — APPROVED** [review]

**Comment by mcollina** [comment]
Can you fix the PR title? the linter is complaining?

**Comment by NMinhNguyen** [comment]
I’m not sure why that is - the error message is complaining about the old title:

> No release type found in pull request title "Make sure `RequestInit` properties are assignable".

I’ll try changing it and back again

**Comment by NMinhNguyen** [comment]
I think all the checks are passing?

**Comment by KhafraDev** [comment]
All the checks here show as successful (which is where I got confused as well), but the [action](https://github.com/nodejs/undici/runs/6462923225?check_suite_focus=true) shows that it's failing:

```
Error: No release type found in pull request title "Make sure `RequestInit` properties are assignable". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/

Available types:
 - feat: A new feature
 - fix: A bug fix
 - docs: Documentation only changes
 - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
 - refactor: A code change that neither fixes a bug nor adds a feature
 - perf: A code change that improves performance
 - test: Adding missing tests or correcting existing tests
 - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
 - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
 - chore: Other changes that don't modify src or test files
 - revert: Reverts a previous commit
```

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
