### PR TITLE
fix: replace socketTimeout with bodyTimeout

### PR DESCRIPTION
**Pull request by ronag**
- Replaces socketTimeout with a bodyTimeout parameter on request.
- Moves headersTimeout to parameter on request.
- Removes socketTimeout.

Removes unecessary retry logic.

Fixes: https://github.com/nodejs/undici/issues/447

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, so much better.

Could you create a 2.x branch for fixes on that line before landing?

**Comment by mcollina** [comment]
I think this should land on master and we keep v2.x for bugfixes on the current line.

**Comment by ronag** [comment]
@mcollina FYI some additional changes:

- Implement headersTimeout in js.
- Remove requestTimeout since it's the same as headersTimeout.
- bodyTimeout and headersTimeout lives on request instead of globally on client.

**Comment by mcollina** [comment]
CI keeps failing.

**Review by mcollina — CHANGES_REQUESTED** [review]
can you please keep an alias to the previous option or throw if that is passed in?

**Comment by ronag** [comment]
> can you please keep an alias to the previous option or throw if that is passed in?

@mcollina fixed

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
