### PR TITLE
feat: add factory option to BalancedPool

### LINKED ISSUE #1220: BalancedPool is missing factory option
`BalancedPool` should have the `factory` option similar to `Pool` and `Agent`.

### PR DESCRIPTION
**Pull request by nipeshkc7**
closes #1220

### CODE REVIEW

**Review by ronag — COMMENTED** [review]
Can you add a test for the factory actually being used?

**Review by ronag — COMMENTED** [review]
Also I see a problem here. The factory options can overlap with the constructor options. Not sure how to resolve that. I think we might have similar issues in the other agents as well. @mcollina wdyt?

**Comment by nipeshkc7** [comment]
> Can you add a test for the factory actually being used?

Sure can do that.

**Comment by mcollina** [comment]
Could you add the option to our docs?

I'm ok with the behavior - I assume the factory can override any of the agent options.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
