### PR TITLE
Revert "fix casing issue when cloning Headers object (#3160)"

### PR DESCRIPTION
**Pull request by tsctx**
Refs: https://github.com/nodejs/undici/pull/3160#issuecomment-2075797019

### CODE REVIEW

**Review by KhafraDev — CHANGES_REQUESTED** [review]
This should be easily fixable by fixing .entries https://github.com/nodejs/undici/blob/034e3f08009120cdc8e811f7e9d0154062147ccb/lib/web/fetch/headers.js#L250 ?

**Comment by tsctx** [comment]
It's impossible because it's an object. It must be an array.

**Comment by KhafraDev** [comment]
We could probably use kHeadersSortedMap (how the iterators run) instead. The webidl part can return an array too.

**Comment by KhafraDev** [comment]
I'll take a look at it in a few hours, fixing it from my point of view doesn't seem too difficult.

**Comment by tsctx** [comment]
This seems not the best solution.

**Pull request closed without merging**
