### PR TITLE
docs: add advanced usage examples for ProxyAgent

### PR DESCRIPTION
**Pull request by mertcanaltin**
I have added additional examples to the ProxyAgent documentation, including how to use ProxyAgent with fetching, custom proxy server setup and HTTPS tunneling.

I would be grateful if you have any suggestions 🚀

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — COMMENTED** [review]
Good work, you should add one example that configures it as a global dispatcher, so that it can be used without passing it.

**Comment by mertcanaltin** [comment]
> Good work, you should add one example that configures it as a global dispatcher, so that it can be used without passing it.

I Added, thanks a lot for the suggestion

**Review by metcoder95 — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
