### PR TITLE
fix: always resume in next tick

### PR DESCRIPTION
**Pull request by ronag**
Fixes: https://github.com/nodejs/undici/issues/394

### CODE REVIEW

**Comment by ronag** [comment]
Needs test and a benchmark run.

**Comment by ronag** [comment]
Might be a better idea to just do `process.nextTick(emitDrain, this)`

**Review by mcollina — APPROVED** [review]
lgtm... are the benchmarks affected?

**Comment by ronag** [comment]
@mcollina: Benchmarks were affected. Made an alternative solution.

**Review by mcollina — APPROVED** [review]
lgtm, does this affect benchmarks?

**Comment by ronag** [comment]
> lgtm, does this affect benchmarks?

Nope

**Pull request merged**
