### PR TITLE
do not reinitalize HeadersList

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Review by anonrig — APPROVED** [review]
Nice stream. LGTM.

**Review by ronag — CHANGES_REQUESTED** [review]
I think the reason this is done to make sure to have a unique copy that the caller can't mutate after passing it.

**Review by KhafraDev — COMMENTED** [review]
@ronag the underlying map gets copied anyways

but I'm wondering what the difference is between what we're already doing? I couldn't stay for the whole stream, sorry. https://github.com/nodejs/undici/blob/9458ffd4f1e5116cdcf8b421a3171d3aded41d46/lib/web/fetch/headers.js#L133-L139

**Comment by mcollina** [comment]
> I think the reason this is done to make sure to have a unique copy that the caller can't mutate after passing it.

@ronag I think we are the caller. No tests or WPT are failing with this change.

**Comment by Uzlopak** [comment]
Funny, i have a similar change stashed locally.
Instead of instanceof we should use a symbolattribute and check for it?

**Review by ronag — APPROVED** [review]

**Comment by tsctx** [comment]
Looks like it needs to be copied. 
https://github.com/nodejs/undici/blob/a8551ad17ead3f35ad9757be090725860f054171/lib/web/fetch/request.js#L140-L141

**Comment by KhafraDev** [comment]
@tsctx good catch, I had to dig very far into the spec to figure out what "A copy of" meant here. That line was added/modified nearly 6 years ago in [this commit](https://github.com/whatwg/fetch/commit/819d8c9d6617986a831ecd9cf21c34ba9589a890), but comments as to why the headerslist were removed since then:

```html
  <p class=note>The headers are sanitised as they might contain headers that are not allowed by this
  mode. Otherwise, they were previously sanitised or are unmodified since creation by a privileged
  API.
```

It appears that when, or if, the internal request mode is modified, some previously allowed headers may be forbidden. Not only do we not implement forbidden headers, but the current code wouldn't satisfy this requirement regardless.

A more correct fix should be what I mentioned previously: https://github.com/nodejs/undici/pull/3150#issuecomment-2070875768, but if that can't be done I don't think there's anything wrong with landing this.

**Comment by tsctx** [comment]
This is also...

```js
import { Request } from "./index.js";

const request = new Request("https://localhost", {
  headers: {
    a: "a",
    b: "b",
  },
});

const childRequest = new Request(request);

[...childRequest.headers.keys()].forEach((key) => childRequest.headers.delete(key));

console.log([...request.headers], [...childRequest.headers]); 
// expected: [ [ 'a', 'a' ], [ 'b', 'b' ] ] []
// actual: [] []
```

**Comment by KhafraDev** [comment]
Makes sense, I'm surprised the tests didn't catch that.

**Review by tsctx — CHANGES_REQUESTED** [review]
No copying can be avoided.

**Comment by KhafraDev** [comment]
@tsctx could you make a PR that tests this so we don't regress?

**Comment by mcollina** [comment]
Closing for now, will revisit later.

(if anybody beats me to it.. go for it!)

**Pull request closed without merging**
