### PR TITLE
fix: include URL hash in fetch calls

### PR DESCRIPTION
**Pull request by galvez**
Fixes https://github.com/nodejs/undici/issues/1245

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ronag — CHANGES_REQUESTED** [review]
I don’t think the hash fragment is supposed to be sent to the server?

**Comment by galvez** [comment]
See my comment — think this is potentially still warranted.

**Comment by mcollina** [comment]
> See my comment — think this is potentially still warranted.

which comment?

**Pull request closed without merging**
