### PR TITLE
perf: bypass method validation

### PR DESCRIPTION
**Pull request by tsctx**
<details>
<summary>Benchmark Script</summary>

```js
import { bench, run } from 'mitata'
import { Request } from '../index.js'
// avoid JIT bias
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})
bench('noop', () => {})

const input = "https://localhost/post"

const method = "post"

bench('new Request(input, { method })', () => {
    return new Request(input, { method })
})

await new Promise((resolve) => setTimeout(resolve, 7000))

await run()

```
</details>

- *main*
```
benchmark                           time (avg)             (min … max)       p75       p99      p995
---------------------------------------------------------------------- -----------------------------
new Request(input, { method })   12.47 µs/iter      (8.5 µs … 2.37 ms)   13.6 µs   27.4 µs   38.4 µs
```

- *this patch*
```
benchmark                           time (avg)             (min … max)       p75       p99      p995
---------------------------------------------------------------------- -----------------------------
new Request(input, { method })   11.79 µs/iter      (8.5 µs … 2.17 ms)   12.1 µs     24 µs     33 µs
```

### CODE REVIEW

**Comment by KhafraDev** [comment]
I don't think it's worth it

**Review by mcollina — APPROVED** [review]
I think it is.

Those objects are created more and more often, and any bits help.

**Review by metcoder95 — APPROVED** [review]

**Comment by mcollina** [comment]
> I don't think it's worth it

@KhafraDev why?

**Comment by KhafraDev** [comment]
if you're fine with it I am fine with it landing

**Pull request merged**
